import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy — Yuno" },
      {
        name: "description",
        content:
          "How Yuno collects, uses and protects personal data for clubs, organizers, promoters and their guests.",
      },
      { property: "og:title", content: "Privacy Policy — Yuno" },
      {
        property: "og:description",
        content: "How Yuno handles personal data across the platform.",
      },
      { property: "og:url", content: "/privacy" },
    ],
    links: [{ rel: "canonical", href: "/privacy" }],
  }),
  component: PrivacyPage,
});

function PrivacyPage() {
  return (
    <section className="pt-24 pb-24 px-6">
      <div className="mx-auto max-w-3xl">
        <span className="inline-block text-xs font-medium uppercase tracking-[0.18em] text-accent border border-accent/40 rounded-full px-3 py-1 mb-6">
          Legal
        </span>
        <h1 className="text-4xl md:text-5xl font-medium tracking-tight text-balance mb-4">
          Privacy Policy
        </h1>
        <p className="text-sm text-muted-foreground mb-10">
          Last updated: June 9, 2026
        </p>

        <div className="rounded-2xl bg-surface ring-1 ring-border p-6 md:p-8 mb-10">
          <p className="text-sm text-muted-foreground leading-relaxed">
            <strong className="text-foreground">This is a placeholder document.</strong>{" "}
            The final, lawyer-reviewed Privacy Policy is on the way. In the meantime, for
            any question about how Yuno handles your data, write to{" "}
            <a className="text-accent hover:underline" href="mailto:contact@yunoapp.eu">
              contact@yunoapp.eu
            </a>
            .
          </p>
        </div>

        <div className="space-y-8 text-sm text-muted-foreground leading-relaxed">
          <div>
            <h2 className="text-xl font-medium text-foreground tracking-tight mb-2">
              What we collect
            </h2>
            <p>
              Account data (name, email, role), operational data generated by your use of
              Yuno (events, orders, table reservations), and the minimum guest data
              required to deliver tickets and Click & Collect orders.
            </p>
          </div>
          <div>
            <h2 className="text-xl font-medium text-foreground tracking-tight mb-2">
              How we use it
            </h2>
            <p>
              To run the platform, process payments through Stripe Connect, send
              transactional notifications, and provide analytics dashboards to venue
              operators, organizers and promoters.
            </p>
          </div>
          <div>
            <h2 className="text-xl font-medium text-foreground tracking-tight mb-2">
              Your rights
            </h2>
            <p>
              Access, rectification, deletion, portability and objection rights under the
              GDPR. Email us to exercise any of them.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
