import type { LandingLang } from "@/i18n/landing-lang";

// Copy of the Yuno CRM signup funnel ("/start?product=crm"): the Claude Design
// project "Yuno CRM" > Inscription.dc.html, in EN / FR / ES. `fr` is the shape.
// No invented claim: the preview cards are labelled as examples, hosting is "in
// the EU" (never "in France"), and nothing here talks about ticketing sold on Yuno.

const fr = {
  meta: {
    title: "Créer mon compte Yuno CRM — 14 jours d’essai, sans carte",
    description:
      "Ouvrez votre console Yuno CRM en 2 minutes : réunissez vos clients, segmentez-les et faites-les revenir. 14 jours d’essai, sans carte bancaire.",
  },
  back: "Retour",
  stepOf: "Étape {n} sur {total}",
  created: "Compte créé",
  haveAccount: "Déjà un compte ?",
  login: "Se connecter",
  email: {
    titlePre: "Lancez votre console en",
    accent: "2 minutes",
    titlePost: ".",
    sub: "Réunissez vos clients, segmentez-les et faites-les revenir. Sans carte bancaire.",
    google: "Avec Google",
    apple: "Avec Apple",
    or: "ou par e-mail",
    label: "E-mail professionnel",
    placeholder: "vous@votreclub.fr",
    errEmpty: "Entrez votre e-mail pour continuer.",
    errBad: "Cette adresse semble incomplète.",
    didYouMean: "Vouliez-vous dire",
    cta: "Continuer",
    busy: "Un instant…",
    termsPre: "En continuant, vous acceptez les",
    cgu: "CGU",
    termsMid: "et la",
    privacy: "politique de confidentialité",
    termsPost: ".",
    trust: ["Sans carte bancaire", "Données hébergées dans l’UE", "Rien à installer"],
    exists: "Cette adresse a déjà un compte Yuno.",
    existsCta: "Connectez-vous",
  },
  password: {
    titlePre: "Choisissez un",
    accent: "mot de passe",
    titlePost: ".",
    sub: "Pour vous connecter avec",
    label: "Mot de passe",
    placeholder: "8 caractères minimum",
    show: "Afficher",
    hide: "Masquer",
    showAria: "Afficher le mot de passe",
    hideAria: "Masquer le mot de passe",
    levels: ["", "Faible", "Moyen", "Bon", "Excellent"],
    rules: ["8 caractères minimum", "Majuscules et minuscules", "Un chiffre ou un symbole"],
    err: "Votre mot de passe doit remplir les 3 conditions.",
  },
  type: {
    titlePre: "Vous organisez des soirées",
    accent: "où",
    titlePost: " ?",
    sub: "On adapte la console à votre activité. Un clic suffit.",
    cta: "Continuer",
    items: [
      {
        id: "club",
        label: "Un club",
        sub: "Un lieu, des soirées chaque semaine",
        noun: "votre club",
        short: "Club",
        ph: "Le Sonar",
      },
      {
        id: "orga",
        label: "Un collectif",
        sub: "Des soirées dans plusieurs lieux",
        noun: "votre collectif",
        short: "Collectif",
        ph: "Nuits Fauves",
      },
      {
        id: "bar",
        label: "Un bar ou un rooftop",
        sub: "Une clientèle fidèle à animer",
        noun: "votre établissement",
        short: "Bar",
        ph: "Le Perchoir",
      },
      {
        id: "fest",
        label: "Un festival",
        sub: "Une ou plusieurs éditions par an",
        noun: "votre festival",
        short: "Festival",
        ph: "Les Nuits d’Été",
      },
    ],
    previewEmpty: "Votre activité",
    previewSub: "Club, collectif, bar ou festival : choisissez à droite.",
  },
  name: {
    titlePre: "Comment s’appelle",
    titlePost: " ?",
    sub: "C’est le nom qui signera vos messages.",
    label: "Nom",
    nameErr: "Ajoutez un nom pour continuer.",
    cityLabel: "Ville",
    optional: "facultatif",
    cityPh: "Paris, Lyon…",
    cities: ["Paris", "Lyon", "Marseille", "Bordeaux", "Lille", "Toulouse"],
    cta: "Continuer",
    typeFallback: "Type d’activité",
    cityFallback: "Ville",
    fallbackName: "Votre établissement",
    campaign: "Campagne « Samedi »",
    example: "SMS · e-mail · Insta",
    funnel: ["Touchés", "Visites", "Achats", "Venus"],
    stats: [
      "de clients qui reviennent",
      "de revenus en plus par mois",
      "de conversion SMS marketing",
    ],
  },
  cap: {
    titlePre: "Combien de personnes par",
    accent: "soirée",
    titlePost: " ?",
    sub: "Pour calibrer vos segments et vos envois. Modifiable à tout moment.",
    people: "personnes",
    perNight: "personnes par soirée",
    skip: "Je ne sais pas encore",
    cta: "Créer mon compte",
    busy: "Création du compte…",
    items: [
      { id: "s", big: "< 200", val: 200 },
      { id: "m", big: "200–500", val: 500 },
      { id: "l", big: "500–1 500", val: 1500 },
      { id: "xl", big: "1 500 +", val: 2000 },
    ],
  },
  code: {
    titlePre: "Vérifiez votre",
    accent: "e-mail",
    titlePost: ".",
    sentTo: "Code à 6 chiffres envoyé à",
    valid: "Valable 10 minutes.",
    linkHint: "Vous pouvez aussi ouvrir le lien présent dans l’e-mail.",
    digit: "Chiffre {n}",
    checking: "Vérification…",
    ok: "E-mail confirmé.",
    bad: "Ce code ne correspond pas. Réessayez.",
    resendIn: "Renvoyer le code dans {t}",
    resend: "Renvoyer le code",
    resent: "Nouveau code envoyé.",
    edit: "Modifier l’e-mail",
    kicker: "Boîte de réception",
    caption: "Rien reçu ? Regardez dans les indésirables.",
    notifTitle: "Yuno",
    notifNow: "maintenant",
    notifCode: "Votre code : 482 917",
    notifNote: "Valable 10 minutes. Ne le partagez pas.",
  },
  done: {
    titlePre: "Votre console est",
    accent: "prête",
    titlePost: ".",
    line: "{name} est enregistré. Il reste une étape : importer vos clients ou connecter votre billetterie actuelle, comptez 2 minutes.",
    primary: "Importer mes clients",
    secondary: "Découvrir la console d’abord",
    opening: "Ouverture de votre console…",
    kicker: "Votre fichier clients",
    caption:
      "Exemple après 3 soirées : chaque client devient un contact que vous pouvez faire revenir.",
    clients: "Clients",
    after: "Après 3 soirées",
    file: "Fichier clients",
    thisMonth: "ce mois",
    returning: "Reviennent",
    afterFirst: "après une 1re soirée",
    reachable: "Joignables",
    reachableBy: "e-mail ou SMS",
    seg: ["Habitués", "Occasionnels", "Nouveaux", "À relancer"],
    relaunch: "{n} clients pas revenus depuis 30 jours",
    relaunchSub: "Une offre pour samedi peut les faire revenir.",
    prepare: "Préparer l’envoi",
    crmTitleNamed: "{first}, vos clients, enfin réunis.",
    crmTitle: "Vos clients, enfin réunis.",
    people: [
      { ini: "LM", name: "Léa M.", meta: "7 soirées · dernière samedi", tag: "Habituée" },
      { ini: "KB", name: "Karim B.", meta: "3 soirées · anniversaire jeudi", tag: "Anniversaire" },
      { ini: "JT", name: "Jade T.", meta: "1re venue · venue avec 4 amis", tag: "Nouvelle" },
    ],
  },
  scenes: {
    email: { k: "Bienvenue", c: "Le CRM et l’outil marketing de la nuit." },
    password: { k: "Sécurité", c: "Un mot de passe solide protège votre fichier clients." },
    type: { k: "Votre activité", c: "La console s’adapte à votre façon de travailler." },
    name: {
      k: "Votre console",
      c: "Chaque matin : qui revient, qui relancer, à qui souhaiter son anniversaire.",
    },
    cap: { k: "Votre public", c: "On calibre vos segments et la taille de vos envois." },
  },
  chips: ["Fichier clients", "Segments", "Campagnes"],
  secure: "Chiffré · hébergé dans l’UE",
  account: "Votre compte Yuno",
  footerHosted: "Données hébergées dans l’UE",
  footerHelp: "Une question ?",
  footerWrite: "Écrivez-nous",
  errors: {
    rate: "Trop de tentatives. Réessayez dans quelques minutes.",
    email: "Cette adresse e-mail n’est pas valide.",
    password: "Ce mot de passe n’est pas accepté. Choisissez-en un plus long.",
    generic: "Impossible de créer le compte pour le moment. Réessayez ou écrivez-nous.",
    oauth: "La connexion n’a pas abouti. Réessayez ou continuez avec votre e-mail.",
  },
};

export type CrmSignupCopy = typeof fr;

const en: CrmSignupCopy = {
  meta: {
    title: "Create my Yuno CRM account — 14-day trial, no card",
    description:
      "Open your Yuno CRM console in 2 minutes: gather your customers, segment them and bring them back. 14-day trial, no credit card.",
  },
  back: "Back",
  stepOf: "Step {n} of {total}",
  created: "Account created",
  haveAccount: "Already have an account?",
  login: "Log in",
  email: {
    titlePre: "Launch your console in",
    accent: "2 minutes",
    titlePost: ".",
    sub: "Gather your customers, segment them and bring them back. No credit card.",
    google: "With Google",
    apple: "With Apple",
    or: "or by email",
    label: "Work email",
    placeholder: "you@yourclub.com",
    errEmpty: "Enter your email to continue.",
    errBad: "This address looks incomplete.",
    didYouMean: "Did you mean",
    cta: "Continue",
    busy: "One moment…",
    termsPre: "By continuing, you accept the",
    cgu: "Terms",
    termsMid: "and the",
    privacy: "privacy policy",
    termsPost: ".",
    trust: ["No credit card", "Data hosted in the EU", "Nothing to install"],
    exists: "This address already has a Yuno account.",
    existsCta: "Log in",
  },
  password: {
    titlePre: "Choose a",
    accent: "password",
    titlePost: ".",
    sub: "To log in with",
    label: "Password",
    placeholder: "8 characters minimum",
    show: "Show",
    hide: "Hide",
    showAria: "Show password",
    hideAria: "Hide password",
    levels: ["", "Weak", "Fair", "Good", "Excellent"],
    rules: ["8 characters minimum", "Upper and lower case", "A digit or a symbol"],
    err: "Your password must meet all 3 conditions.",
  },
  type: {
    titlePre: "Where do you run",
    accent: "nights",
    titlePost: "?",
    sub: "We adapt the console to what you do. One click is enough.",
    cta: "Continue",
    items: [
      {
        id: "club",
        label: "A club",
        sub: "One venue, nights every week",
        noun: "your club",
        short: "Club",
        ph: "Le Sonar",
      },
      {
        id: "orga",
        label: "A collective",
        sub: "Nights across several venues",
        noun: "your collective",
        short: "Collective",
        ph: "Nuits Fauves",
      },
      {
        id: "bar",
        label: "A bar or rooftop",
        sub: "A loyal crowd to keep warm",
        noun: "your venue",
        short: "Bar",
        ph: "Le Perchoir",
      },
      {
        id: "fest",
        label: "A festival",
        sub: "One or more editions a year",
        noun: "your festival",
        short: "Festival",
        ph: "Summer Nights",
      },
    ],
    previewEmpty: "Your activity",
    previewSub: "Club, collective, bar or festival: pick on the right.",
  },
  name: {
    titlePre: "What is",
    titlePost: " called?",
    sub: "It's the name that will sign your messages.",
    label: "Name",
    nameErr: "Add a name to continue.",
    cityLabel: "City",
    optional: "optional",
    cityPh: "London, Madrid…",
    cities: ["Paris", "London", "Madrid", "Barcelona", "Lyon", "Berlin"],
    cta: "Continue",
    typeFallback: "Type of activity",
    cityFallback: "City",
    fallbackName: "Your venue",
    campaign: "“Saturday” campaign",
    example: "SMS · email · Insta",
    funnel: ["Reached", "Visits", "Purchases", "Came"],
    stats: ["of customers who come back", "more revenue per month", "SMS marketing conversion"],
  },
  cap: {
    titlePre: "How many people per",
    accent: "night",
    titlePost: "?",
    sub: "To calibrate your segments and sends. You can change it any time.",
    people: "people",
    perNight: "people per night",
    skip: "I don't know yet",
    cta: "Create my account",
    busy: "Creating your account…",
    items: [
      { id: "s", big: "< 200", val: 200 },
      { id: "m", big: "200–500", val: 500 },
      { id: "l", big: "500–1,500", val: 1500 },
      { id: "xl", big: "1,500 +", val: 2000 },
    ],
  },
  code: {
    titlePre: "Check your",
    accent: "email",
    titlePost: ".",
    sentTo: "6-digit code sent to",
    valid: "Valid for 10 minutes.",
    linkHint: "You can also open the link in the email.",
    digit: "Digit {n}",
    checking: "Checking…",
    ok: "Email confirmed.",
    bad: "That code doesn't match. Try again.",
    resendIn: "Resend the code in {t}",
    resend: "Resend the code",
    resent: "New code sent.",
    edit: "Change email",
    kicker: "Inbox",
    caption: "Nothing yet? Check your spam folder.",
    notifTitle: "Yuno",
    notifNow: "now",
    notifCode: "Your code: 482 917",
    notifNote: "Valid for 10 minutes. Don't share it.",
  },
  done: {
    titlePre: "Your console is",
    accent: "ready",
    titlePost: ".",
    line: "{name} is registered. One step left: import your customers or connect your current ticketing, it takes about 2 minutes.",
    primary: "Import my customers",
    secondary: "Explore the console first",
    opening: "Opening your console…",
    kicker: "Your customer file",
    caption: "Example after 3 nights: every customer becomes a contact you can bring back.",
    clients: "Customers",
    after: "After 3 nights",
    file: "Customer file",
    thisMonth: "this month",
    returning: "Come back",
    afterFirst: "after a first night",
    reachable: "Reachable",
    reachableBy: "email or SMS",
    seg: ["Regulars", "Occasional", "New", "To win back"],
    relaunch: "{n} customers haven't been back in 30 days",
    relaunchSub: "An offer for Saturday can bring them back.",
    prepare: "Prepare the send",
    crmTitleNamed: "{first}, your customers, finally in one place.",
    crmTitle: "Your customers, finally in one place.",
    people: [
      { ini: "LM", name: "Léa M.", meta: "7 nights · last Saturday", tag: "Regular" },
      { ini: "KB", name: "Karim B.", meta: "3 nights · birthday Thursday", tag: "Birthday" },
      { ini: "JT", name: "Jade T.", meta: "First visit · came with 4 friends", tag: "New" },
    ],
  },
  scenes: {
    email: { k: "Welcome", c: "The CRM and marketing tool for nightlife." },
    password: { k: "Security", c: "A strong password protects your customer file." },
    type: { k: "Your activity", c: "The console adapts to the way you work." },
    name: {
      k: "Your console",
      c: "Every morning: who's coming back, who to follow up, whose birthday it is.",
    },
    cap: { k: "Your crowd", c: "We calibrate your segments and the size of your sends." },
  },
  chips: ["Customer file", "Segments", "Campaigns"],
  secure: "Encrypted · hosted in the EU",
  account: "Your Yuno account",
  footerHosted: "Data hosted in the EU",
  footerHelp: "A question?",
  footerWrite: "Write to us",
  errors: {
    rate: "Too many attempts. Try again in a few minutes.",
    email: "This email address isn't valid.",
    password: "This password isn't accepted. Choose a longer one.",
    generic: "We can't create the account right now. Try again or write to us.",
    oauth: "Sign-in didn't go through. Try again or continue with your email.",
  },
};

const es: CrmSignupCopy = {
  meta: {
    title: "Crear mi cuenta de Yuno CRM — 14 días de prueba, sin tarjeta",
    description:
      "Abre tu consola de Yuno CRM en 2 minutos: reúne a tus clientes, segméntalos y haz que vuelvan. 14 días de prueba, sin tarjeta.",
  },
  back: "Volver",
  stepOf: "Paso {n} de {total}",
  created: "Cuenta creada",
  haveAccount: "¿Ya tienes cuenta?",
  login: "Entrar",
  email: {
    titlePre: "Lanza tu consola en",
    accent: "2 minutos",
    titlePost: ".",
    sub: "Reúne a tus clientes, segméntalos y haz que vuelvan. Sin tarjeta.",
    google: "Con Google",
    apple: "Con Apple",
    or: "o por e-mail",
    label: "E-mail profesional",
    placeholder: "tu@tuclub.es",
    errEmpty: "Escribe tu e-mail para continuar.",
    errBad: "Esta dirección parece incompleta.",
    didYouMean: "¿Querías decir",
    cta: "Continuar",
    busy: "Un momento…",
    termsPre: "Al continuar, aceptas las",
    cgu: "condiciones",
    termsMid: "y la",
    privacy: "política de privacidad",
    termsPost: ".",
    trust: ["Sin tarjeta", "Datos alojados en la UE", "Nada que instalar"],
    exists: "Esta dirección ya tiene una cuenta de Yuno.",
    existsCta: "Entra",
  },
  password: {
    titlePre: "Elige una",
    accent: "contraseña",
    titlePost: ".",
    sub: "Para entrar con",
    label: "Contraseña",
    placeholder: "8 caracteres como mínimo",
    show: "Mostrar",
    hide: "Ocultar",
    showAria: "Mostrar la contraseña",
    hideAria: "Ocultar la contraseña",
    levels: ["", "Débil", "Media", "Buena", "Excelente"],
    rules: ["8 caracteres como mínimo", "Mayúsculas y minúsculas", "Un número o un símbolo"],
    err: "Tu contraseña debe cumplir las 3 condiciones.",
  },
  type: {
    titlePre: "¿Dónde organizas",
    accent: "fiestas",
    titlePost: "?",
    sub: "Adaptamos la consola a tu actividad. Basta un clic.",
    cta: "Continuar",
    items: [
      {
        id: "club",
        label: "Un club",
        sub: "Un local, fiestas cada semana",
        noun: "tu club",
        short: "Club",
        ph: "Le Sonar",
      },
      {
        id: "orga",
        label: "Un colectivo",
        sub: "Fiestas en varios locales",
        noun: "tu colectivo",
        short: "Colectivo",
        ph: "Noches Fieras",
      },
      {
        id: "bar",
        label: "Un bar o una azotea",
        sub: "Una clientela fiel que animar",
        noun: "tu local",
        short: "Bar",
        ph: "La Terraza",
      },
      {
        id: "fest",
        label: "Un festival",
        sub: "Una o varias ediciones al año",
        noun: "tu festival",
        short: "Festival",
        ph: "Noches de Verano",
      },
    ],
    previewEmpty: "Tu actividad",
    previewSub: "Club, colectivo, bar o festival: elige a la derecha.",
  },
  name: {
    titlePre: "¿Cómo se llama",
    titlePost: "?",
    sub: "Es el nombre que firmará tus mensajes.",
    label: "Nombre",
    nameErr: "Añade un nombre para continuar.",
    cityLabel: "Ciudad",
    optional: "opcional",
    cityPh: "Madrid, Barcelona…",
    cities: ["Madrid", "Barcelona", "Valencia", "Sevilla", "Bilbao", "Málaga"],
    cta: "Continuar",
    typeFallback: "Tipo de actividad",
    cityFallback: "Ciudad",
    fallbackName: "Tu local",
    campaign: "Campaña «Sábado»",
    example: "SMS · e-mail · Insta",
    funnel: ["Alcanzados", "Visitas", "Compras", "Vinieron"],
    stats: ["de clientes que vuelven", "más de ingresos al mes", "de conversión de SMS"],
  },
  cap: {
    titlePre: "¿Cuánta gente por",
    accent: "fiesta",
    titlePost: "?",
    sub: "Para calibrar tus segmentos y tus envíos. Modificable cuando quieras.",
    people: "personas",
    perNight: "personas por fiesta",
    skip: "Aún no lo sé",
    cta: "Crear mi cuenta",
    busy: "Creando la cuenta…",
    items: [
      { id: "s", big: "< 200", val: 200 },
      { id: "m", big: "200–500", val: 500 },
      { id: "l", big: "500–1.500", val: 1500 },
      { id: "xl", big: "1.500 +", val: 2000 },
    ],
  },
  code: {
    titlePre: "Revisa tu",
    accent: "e-mail",
    titlePost: ".",
    sentTo: "Código de 6 cifras enviado a",
    valid: "Válido 10 minutos.",
    linkHint: "También puedes abrir el enlace del e-mail.",
    digit: "Cifra {n}",
    checking: "Comprobando…",
    ok: "E-mail confirmado.",
    bad: "Ese código no coincide. Inténtalo de nuevo.",
    resendIn: "Reenviar el código en {t}",
    resend: "Reenviar el código",
    resent: "Nuevo código enviado.",
    edit: "Cambiar el e-mail",
    kicker: "Bandeja de entrada",
    caption: "¿No llega nada? Mira en el correo no deseado.",
    notifTitle: "Yuno",
    notifNow: "ahora",
    notifCode: "Tu código: 482 917",
    notifNote: "Válido 10 minutos. No lo compartas.",
  },
  done: {
    titlePre: "Tu consola está",
    accent: "lista",
    titlePost: ".",
    line: "{name} está registrado. Queda un paso: importar a tus clientes o conectar tu venta de entradas actual, unos 2 minutos.",
    primary: "Importar a mis clientes",
    secondary: "Descubrir primero la consola",
    opening: "Abriendo tu consola…",
    kicker: "Tu archivo de clientes",
    caption:
      "Ejemplo tras 3 fiestas: cada cliente pasa a ser un contacto al que puedes hacer volver.",
    clients: "Clientes",
    after: "Tras 3 fiestas",
    file: "Archivo de clientes",
    thisMonth: "este mes",
    returning: "Vuelven",
    afterFirst: "tras una 1.ª fiesta",
    reachable: "Localizables",
    reachableBy: "e-mail o SMS",
    seg: ["Habituales", "Ocasionales", "Nuevos", "A recuperar"],
    relaunch: "{n} clientes no han vuelto en 30 días",
    relaunchSub: "Una oferta para el sábado puede hacerlos volver.",
    prepare: "Preparar el envío",
    crmTitleNamed: "{first}, tus clientes, por fin juntos.",
    crmTitle: "Tus clientes, por fin juntos.",
    people: [
      { ini: "LM", name: "Léa M.", meta: "7 fiestas · última el sábado", tag: "Habitual" },
      { ini: "KB", name: "Karim B.", meta: "3 fiestas · cumple el jueves", tag: "Cumpleaños" },
      { ini: "JT", name: "Jade T.", meta: "1.ª vez · vino con 4 amigos", tag: "Nueva" },
    ],
  },
  scenes: {
    email: { k: "Bienvenida", c: "El CRM y la herramienta de marketing de la noche." },
    password: { k: "Seguridad", c: "Una contraseña sólida protege tu archivo de clientes." },
    type: { k: "Tu actividad", c: "La consola se adapta a tu forma de trabajar." },
    name: {
      k: "Tu consola",
      c: "Cada mañana: quién vuelve, a quién recuperar, a quién felicitar.",
    },
    cap: { k: "Tu público", c: "Calibramos tus segmentos y el tamaño de tus envíos." },
  },
  chips: ["Archivo de clientes", "Segmentos", "Campañas"],
  secure: "Cifrado · alojado en la UE",
  account: "Tu cuenta de Yuno",
  footerHosted: "Datos alojados en la UE",
  footerHelp: "¿Una pregunta?",
  footerWrite: "Escríbenos",
  errors: {
    rate: "Demasiados intentos. Inténtalo de nuevo en unos minutos.",
    email: "Esta dirección de e-mail no es válida.",
    password: "Esta contraseña no se acepta. Elige una más larga.",
    generic: "No podemos crear la cuenta ahora mismo. Inténtalo de nuevo o escríbenos.",
    oauth: "No se pudo iniciar sesión. Inténtalo de nuevo o continúa con tu e-mail.",
  },
};

export const crmSignupContent: Record<LandingLang, CrmSignupCopy> = { fr, en, es };
