// Yuno CRM — the landing for clubs and organizers who KEEP their ticketing
// (Shotgun first). Separate product from the main landing (which sells the
// ticketing Suite): its own story, its own paid pricing and its own signup
// (SignupFlow product="crm").
//
// Layout: the Insyder grammar (floating pill nav, centred hero + live product
// frame, proof marquee, problem, night block, sticky steps, channels, "they give
// you / Yuno gives you" switch, bento, pricing, FAQ, final call) rebuilt on the
// Yuno design system (Claude Design project "Design system Yuno créé").
//
// Facts must match the yuno repo: one subscription (29 € HT launch price, 39 €
// later for new accounts, annual = 12 months + 30,000 Yunits), 10,000 Yunits a
// month, 14-day trial with 5,000 Yunits and no card, recharges at 500 Yunits per
// euro with +10 % / +15 % bonuses (src/lib/crmPlans.ts, _shared/crm-billing.ts,
// crm_pricing_config). Data lives in the EU (Supabase eu-west-1), never write
// "hosted in France". Instagram data is never read: Instagram DM and WhatsApp
// are "soon" channels only. Meta audiences are "soon". SMS and the MCP server
// (ChatGPT, Claude, Gemini) are presented as live (Paul, 4 Oct 2026).
//
// `title` + `accent`: the accent is a substring of the title, painted with the
// brand gradient (one accented word or phrase per headline).

type Pill = {
  ini: string;
  name: string;
  meta: string;
  tag: string;
  tone: "hot" | "warm" | "new" | "cold";
};

const fr = {
  meta: {
    title: "Yuno CRM — Sachez qui vient à vos soirées, et faites-les revenir",
    description:
      "Yuno CRM se branche sur Shotgun et regroupe vos acheteurs dans un seul fichier clients : habitués, nouveaux, à relancer. E-mails, SMS, bilans de soirée. 29 € HT par mois, 14 jours d’essai sans carte.",
  },
  whatsappMessage:
    "Bonjour Paul 👋 Je vends sur Shotgun et j’aimerais en savoir plus sur Yuno CRM.",
  nav: {
    links: [
      { label: "Fonctionnalités", href: "#fonctionnalites" },
      { label: "Comment ça marche", href: "#etapes" },
      { label: "Tarifs", href: "#tarifs" },
      { label: "FAQ", href: "#faq" },
    ],
    cta: "Essayer 14 jours",
    login: "Se connecter",
    menu: "Menu",
    close: "Fermer",
  },
  hero: {
    eyebrowTag: "Yuno CRM",
    eyebrow: "Branché à Shotgun en 2 minutes",
    title: "Sachez qui vient à vos soirées. Et faites-les revenir.",
    accent: "revenir",
    sub: "Yuno regroupe tous vos acheteurs Shotgun dans un seul fichier clients, puis vous aide à les retrouver, à leur écrire par e-mail et SMS, et à voir ce qui remplit votre salle.",
    cta: "Essayer 14 jours gratuitement",
    trust: ["Connexion par l’API Shotgun", "Prêt en 2 minutes", "Sans carte bancaire"],
    frameUrl: "yunoapp.eu/crm",
    live: "En direct",
    toasts: [
      { title: "Camille revient pour la 4ᵉ fois", sub: "Habituée · Techno Night" },
      { title: "« Last call » programmé à 18:00", sub: "6 120 contacts · 6 120 Yunits" },
      { title: "▲ 36 billets aujourd’hui", sub: "Synchro Shotgun · il y a 2 min" },
    ],
  },
  dash: {
    venue: "Le Bunker",
    venueSub: "Paris 11e · Club",
    nav: {
      groups: ["Piloter", "Agir", "Connaître"],
      home: "Accueil",
      analyses: "Analyses",
      campaigns: "Campagnes",
      nights: "Soirées",
      clients: "Clients",
      connectors: "Connecteurs",
      settings: "Réglages",
      help: "Aide",
      yunits: "Yunits",
      yunitsSub: "8 940 disponibles",
    },
    search: "Rechercher un client, une campagne…",
    sync: "Shotgun synchronisé · 18:38",
    yunitsWord: "Yunits",
    date: "Samedi 3 octobre",
    hello: "Bonjour Nina",
    subtitle: "3 actions pour aujourd’hui, dont une avant 18:00.",
    see: "Voir ↓",
    newCampaign: "Nouvelle campagne",
    mission: {
      label: "Rapport de mission · 30 sept.",
      title: "« Line-up Techno Night » a fait venir 1 120 personnes sur votre page.",
      sub: "214 inscriptions et 61 achats venus de ces visites · 6 040 Yunits dépensés.",
      link: "Voir le détail",
    },
    sales: {
      title: "Combien ai-je vendu ?",
      unit: "Ventes par jour, remboursements déduits",
      periods: [
        {
          k: "7 j",
          label: "7 derniers jours",
          vs: "les 7 jours précédents",
          tot: 11480,
          d: 0.08,
          n: 7,
        },
        {
          k: "30 j",
          label: "30 derniers jours",
          vs: "les 30 jours précédents",
          tot: 38940,
          d: 0.12,
          n: 30,
        },
        {
          k: "90 j",
          label: "90 derniers jours",
          vs: "les 90 jours précédents",
          tot: 104300,
          d: 0.05,
          n: 45,
        },
      ],
      moreSub: "Soit {n} de plus",
      legend: ["Ventes du jour", "Période précédente", "Envoi d’un message"],
      insight:
        "Les 2 jours qui suivent un envoi, vous vendez en moyenne 2,4 fois plus que le reste du temps.",
      tipPrev: "Période précédente : {n}",
      sends: [
        "Line-up Techno Night · e-mail",
        "Prévente Warehouse · e-mail",
        "Rappel aux habitués · SMS",
      ],
    },
    kpis: [
      {
        label: "Clients",
        value: "18 420",
        delta: "▲ 36 aujourd’hui",
        note: "Contacts uniques, doublons fusionnés",
      },
      {
        label: "Habitués",
        value: "2 140",
        delta: "▲ 12 ce mois-ci",
        note: "Venus 3 fois ou plus · 6 derniers mois",
      },
      {
        label: "Taux de conversion",
        value: "9 %",
        delta: "▲ 1,4 pt vs l’envoi d’avant",
        note: "Ont acheté dans les 48 h après « Line-up Techno Night »",
      },
      {
        label: "Joignables",
        value: "86 %",
        delta: "15 880 sur 18 420 clients",
        note: "Clients qu’un message peut atteindre",
      },
    ],
    reach: ["E-mail + SMS 71 %", "Aucun 14 %"],
    night: {
      label: "Prochaine soirée",
      when: "Ce soir · 23:00",
      name: "Techno Night",
      place: "Le Bunker · samedi 3 octobre",
      of: "sur 1 000 places",
      today: "▲ 36 aujourd’hui",
      axis: ["26 sept.", "Ce soir"],
      legend: ["Cette soirée", "Techno Night du 12 sept.", "Avance"],
      insight:
        "Vous êtes **5 % devant** votre dernière soirée au même moment. À ce rythme : **environ 960** places ce soir.",
    },
    who: {
      title: "Qui achète ?",
      sub: "Les 842 acheteurs de Techno Night",
      center: "acheteurs",
      rows: [
        { l: "Habitués", sub: "Venus 3 fois ou plus", n: 236, p: 28 },
        { l: "Occasionnels", sub: "Moins de 3 soirées", n: 286, p: 34 },
        { l: "Nouveaux", sub: "Leur 1ʳᵉ soirée", n: 320, p: 38 },
      ],
      buyers: "acheteurs",
      note: "Près de 4 acheteurs sur 10 sont **nouveaux** : c’est le moment de leur donner une raison de revenir.",
      link: "Préparer un message de bienvenue",
    },
    todo: {
      title: "Que faut-il faire aujourd’hui ?",
      items: [
        {
          badge: "Aujourd’hui",
          title: "Relancer 214 habitués sans place",
          why: "Venus 3 fois ou plus, joignables. La soirée, c’est ce soir.",
          cta: "Préparer la relance",
          primary: true,
        },
        {
          badge: "Avant 18:00",
          title: "Valider « Last call — Techno Night »",
          why: "Brouillon complet, prévu à 18:00 pour 6 120 contacts.",
          cta: "Relire et valider",
          primary: false,
        },
        {
          badge: "Cette semaine",
          title: "Prévoir une recharge de Yunits",
          why: "Après 18:00 il restera 2 820 Yunits : assez pour des e-mails, pas pour un SMS à tous.",
          cta: "Recharger",
          primary: false,
        },
      ],
    },
  },
  proof: {
    line: "Chaque acheteur Shotgun devient une fiche. Avec son historique, sa fidélité, et une bonne raison de lui écrire.",
    pills: [
      {
        ini: "CR",
        name: "Camille R.",
        meta: "7 soirées · vue le 14 sept.",
        tag: "Habituée",
        tone: "hot",
      },
      {
        ini: "YB",
        name: "Yanis B.",
        meta: "4 soirées · vu le 7 sept.",
        tag: "Habitué",
        tone: "hot",
      },
      { ini: "IM", name: "Inès M.", meta: "1ʳᵉ soirée · hier", tag: "Nouvelle", tone: "new" },
      {
        ini: "LD",
        name: "Lucas D.",
        meta: "3 soirées · il y a 5 mois",
        tag: "À relancer",
        tone: "cold",
      },
      {
        ini: "SD",
        name: "Sarah D.",
        meta: "11 soirées · vue samedi",
        tag: "Habituée",
        tone: "hot",
      },
      {
        ini: "HM",
        name: "Hugo M.",
        meta: "2 soirées · vu le 30 août",
        tag: "Occasionnel",
        tone: "warm",
      },
      {
        ini: "NK",
        name: "Nora K.",
        meta: "1ʳᵉ soirée · Techno Night",
        tag: "Nouvelle",
        tone: "new",
      },
      {
        ini: "TG",
        name: "Théo G.",
        meta: "5 soirées · il y a 3 mois",
        tag: "À relancer",
        tone: "cold",
      },
      {
        ini: "LP",
        name: "Léa P.",
        meta: "9 soirées · vue le 26 sept.",
        tag: "Habituée",
        tone: "hot",
      },
      {
        ini: "AB",
        name: "Adam B.",
        meta: "2 soirées · vu le 12 sept.",
        tag: "Occasionnel",
        tone: "warm",
      },
    ] as Pill[],
    connected: "Connecté à votre compte Shotgun",
    facts: [
      {
        title: "Tout l’historique",
        body: "Soirées, billets et acheteurs importés dès la connexion.",
      },
      {
        title: "Mis à jour en continu",
        body: "Chaque nouveau billet arrive tout seul dans votre fichier.",
      },
      {
        title: "Lecture seule",
        body: "Yuno ne modifie, ne rembourse et ne publie rien chez Shotgun.",
      },
    ],
  },
  problem: {
    eyebrow: "Le problème",
    title: "Votre prochain habitué est déjà venu 3 fois. Vous ne savez juste pas qui c’est.",
    accent: "qui c’est",
    sub: "Une billetterie vous dit combien de billets sont partis. Pas qui revient, pas qui a disparu, pas qui relancer.",
    cards: [
      {
        title: "Vos ventes ne disent rien de vos clients.",
        body: "Combien de visites avant l’achat, d’où ils viennent, où ils décrochent : Yuno montre le parcours, pas juste le billet.",
      },
      {
        title: "Le même e-mail pour tout le monde. Personne ne clique.",
        body: "Yuno adapte e-mails et SMS à chaque client, boostés par l’IA et des automatisations.",
      },
    ],
  },
  night: {
    title: "Vos billets savent déjà qui revient. Maintenant, vous aussi.",
    accent: "vous aussi",
    sub: "Chaque billet laisse un nom, une date, une soirée. Yuno rassemble tout dans un seul fichier, fusionne les doublons et classe vos clients par fidélité. Il se met à jour tout seul.",
    table: {
      title: "Tous les clients",
      sub: "18 420 contacts uniques · classés par fidélité",
      search: "Rechercher un client",
      filters: ["Tous", "Habitués", "Nouveaux", "À relancer"],
      export: "Exporter",
      cols: ["Client", "Soirées", "Dernière venue", "Fidélité", "Joignable", "Statut"],
      rows: [
        {
          ini: "SD",
          name: "Sarah Dubois",
          sub: "Paris 11e",
          nights: 11,
          last: "3 oct.",
          score: 98,
          reach: "E-mail · SMS",
          tag: "Habituée",
          tone: "hot",
        },
        {
          ini: "CL",
          name: "Camille Laurent",
          sub: "Montreuil",
          nights: 14,
          last: "26 sept.",
          score: 96,
          reach: "E-mail · SMS",
          tag: "Habituée",
          tone: "hot",
        },
        {
          ini: "LP",
          name: "Léa Petit",
          sub: "Paris 20e",
          nights: 9,
          last: "26 sept.",
          score: 91,
          reach: "E-mail",
          tag: "Habituée",
          tone: "hot",
        },
        {
          ini: "HM",
          name: "Hugo Marchand",
          sub: "Paris 18e",
          nights: 9,
          last: "12 sept.",
          score: 88,
          reach: "E-mail · SMS",
          tag: "Habitué",
          tone: "hot",
        },
        {
          ini: "TG",
          name: "Théo Garnier",
          sub: "Vincennes",
          nights: 5,
          last: "4 juil.",
          score: 64,
          reach: "E-mail",
          tag: "À relancer",
          tone: "cold",
        },
        {
          ini: "AB",
          name: "Adam Benali",
          sub: "Paris 10e",
          nights: 2,
          last: "12 sept.",
          score: 41,
          reach: "SMS",
          tag: "Occasionnel",
          tone: "warm",
        },
        {
          ini: "NK",
          name: "Nora Kaci",
          sub: "Saint-Ouen",
          nights: 1,
          last: "3 oct.",
          score: 22,
          reach: "E-mail · SMS",
          tag: "Nouvelle",
          tone: "new",
        },
        {
          ini: "YH",
          name: "Yanis Haddad",
          sub: "Paris 13e",
          nights: 1,
          last: "3 oct.",
          score: 20,
          reach: "E-mail",
          tag: "Nouveau",
          tone: "new",
        },
      ],
    },
    chipsTitle: "Ne laissez plus filer personne",
    chips: [
      [
        "Habitués",
        "Nouveaux",
        "À relancer",
        "Gros fidèles",
        "Doublons fusionnés",
        "Fiche par client",
        "Import CSV ou Excel",
        "Recherche en 2 secondes",
      ],
      [
        "Bilan de soirée",
        "Comparé à la soirée d’avant",
        "Qui achète",
        "Rythme des ventes",
        "Ventes après un envoi",
        "Prochaine soirée",
        "Export à tout moment",
      ],
      [
        "Campagnes e-mail",
        "SMS",
        "Modèles prêts",
        "Envois programmés",
        "Coût affiché avant l’envoi",
        "Désinscription gérée",
        "Équipe sans limite",
        "MCP · ChatGPT, Claude, Gemini",
        "Audiences Meta · bientôt",
      ],
    ],
    cta: "Connecter mon compte Shotgun",
  },
  steps: {
    eyebrow: "Comment ça marche",
    title: "Yuno en 2 minutes.",
    accent: "2 minutes",
    sub: "Vous connectez, Yuno range tout. Vous n’avez rien à saisir : vos clients sont prêts avant la fin de votre café.",
    cta: "Connecter mon compte Shotgun",
    stepWord: "Étape",
    items: [
      {
        title: "Connectez Shotgun.",
        body: "Collez votre ID organisateur et votre jeton API, générés dans vos intégrations Shotgun. Pas de mot de passe.",
      },
      {
        title: "Yuno range tout.",
        body: "Soirées, billets et acheteurs sont importés, regroupés par personne et classés par fidélité. Ensuite, tout se met à jour seul.",
      },
      {
        title: "Ouvrez. Voyez. Relancez.",
        body: "Chaque matin : ce qui a vendu, qui relancer, ce qui demande votre attention. Vous n’analysez plus, vous agissez.",
      },
    ],
    connect: {
      title: "Connecter Shotgun",
      sub: "Lecture seule. Rien ne change chez Shotgun.",
      id: "ID organisateur",
      idVal: "48213",
      token: "Jeton API",
      help: "Où trouver mon jeton ?",
      btn: "Connecter",
      busy: "Vérification…",
      ok: "Connecté · synchro toutes les 15 min",
    },
    sort: {
      title: "Import de votre historique",
      sub: "Yuno range vos clients, vous n’avez rien à faire.",
      rows: [
        { label: "Soirées importées", n: 38 },
        { label: "Billets importés", n: 24812 },
        { label: "Clients regroupés", n: 18420 },
        { label: "Doublons fusionnés", n: 3106 },
      ],
      done: "Historique Shotgun importé",
    },
  },
  channels: {
    eyebrow: "Les envois",
    title: "Vos clients. Vos messages. Un seul compteur.",
    accent: "compteur",
    sub: "Écrivez au bon segment par e-mail ou SMS, voyez le coût avant d’envoyer, programmez. Aujourd’hui l’e-mail et le SMS, demain Instagram et WhatsApp : même endroit, même compteur.",
    cta: "Essayer 14 jours gratuitement",
    composer: {
      title: "Nouveau message",
      to: "À",
      cost: "Coût",
      after: "Solde après l’envoi",
      schedule: "Samedi · 18:00",
      send: "Programmer",
      subject: "Objet",
      messages: [
        {
          seg: "Habitués",
          count: 1284,
          channel: "E-mail",
          subject: "Samedi, on remet ça.",
          text: "Ça fait trois soirées qu’on se croise. Votre place vous attend samedi, avant tout le monde.",
        },
        {
          seg: "Nouveaux",
          count: 320,
          channel: "SMS",
          subject: "",
          text: "Merci d’être venu(e) à Techno Night ! Prochaine date le 17 : yuno.fr/bunker",
        },
        {
          seg: "Endormis",
          count: 740,
          channel: "E-mail",
          subject: "On vous a gardé une place.",
          text: "Ça fait un moment. Warehouse Sessions, vendredi 9 : la prévente ouvre pour vous d’abord.",
        },
      ],
      balance: 8940,
    },
    rates: [
      { name: "E-mail", cost: "1 Yunit", soon: false },
      { name: "SMS", cost: "40 Yunits", soon: false },
      { name: "DM Instagram", cost: "Bientôt", soon: true },
      { name: "WhatsApp", cost: "Bientôt", soon: true },
    ],
    footnote:
      "Les tests d’envoi sont gratuits. Yuno écarte les contacts déjà trop sollicités, sans vous les compter.",
  },
  mcp: {
    eyebrow: "Intégrations",
    title: "Vos données. Votre IA. Grâce au MCP.",
    accent: "MCP",
    sub: "Connectez Yuno à ChatGPT, Claude, Gemini et bien d’autres pour transformer vos clients et vos ventes en analyses instantanées.",
    cta: "Essayer 14 jours gratuitement",
    stage: "L’IA au service de vos soirées",
    stageAccent: "vos soirées",
    placeholder: "Quelles données de vos clients voulez-vous analyser ?",
    models: ["Claude", "ChatGPT", "Gemini"],
    via: "via le MCP de Yuno",
    convo: [
      {
        q: "Qui sont mes habitués qui ne sont pas revenus depuis 2 mois ?",
        a: "214 habitués n’ont rien acheté depuis 60 jours, dont 168 joignables par e-mail. Je vous prépare le segment « À relancer » ?",
      },
      {
        q: "Quelle soirée a fait venir le plus de nouveaux en septembre ?",
        a: "Techno Night du 12 sept. : 312 nouveaux clients, soit 39 % des acheteurs. Warehouse Sessions suit avec 204.",
      },
      {
        q: "Mes ventes de Techno Night sont-elles en avance sur la dernière ?",
        a: "Oui : 842 places ce soir contre 802 au même moment le 12 sept., soit 5 % d’avance. À ce rythme, environ 960 places.",
      },
    ],
    chips: ["Analyser", "Segmenter", "Écrire", "Comparer", "Prévoir"],
  },
  compare: {
    title:
      "Votre billetterie vous dit combien de billets sont partis. Yuno vous dit qui relancer pour remplir la prochaine.",
    accent: "qui relancer pour remplir la prochaine",
    tabs: ["Votre billetterie vous donne", "Yuno vous donne"],
    left: {
      title: "Ce que votre billetterie vous donne",
      items: [
        "Un total de billets par soirée",
        "Un export à rouvrir à chaque fois",
        "Les mêmes personnes dans dix fichiers",
        "Aucune idée de qui revient",
      ],
    },
    right: {
      title: "Ce que Yuno vous donne",
      items: [
        "Qui revient, et combien de fois",
        "Une fiche par personne, pour toujours",
        "Les habitués qui décrochent",
        "Des segments prêts à recevoir un message",
        "Le bilan de chaque soirée",
      ],
    },
    cta: "Essayer 14 jours gratuitement",
  },
  bento: {
    eyebrow: "Fonctionnalités",
    title: "Tout ce que votre billetterie ne vous montre pas.",
    accent: "montre pas",
    sub: "Un outil pensé pour une seule chose : transformer vos acheteurs en habitués.",
    cta: "Essayer 14 jours gratuitement",
    clients: {
      title: "Fichier clients",
      body: "Chaque acheteur devient une fiche, avec toutes ses soirées. Doublons fusionnés, n’importe qui retrouvé en 2 secondes.",
      search: "Rechercher un client",
    },
    segments: {
      title: "Segments",
      body: "Habitués, nouveaux, endormis : chacun dans la bonne liste. Elles se mettent à jour toutes seules.",
      rows: [
        { l: "Habitués", n: 1284, w: 100 },
        { l: "Nouveaux", n: 962, w: 75 },
        { l: "Endormis", n: 740, w: 58 },
        { l: "Gros fidèles", n: 118, w: 14 },
      ],
      action: "Écrire aux endormis",
    },
    relance: {
      title: "Habitués à relancer",
      body: "Yuno repère ceux qui décrochent et vous tend la liste. Chaque message part vers quelqu’un qui connaît déjà vos soirées.",
      list: "À relancer · 214",
    },
    bilans: {
      title: "Bilans de soirée",
      body: "Chaque soirée comparée à la précédente, au même moment. Vous savez enfin quel message a fait vendre.",
      legend: ["Cette soirée", "Vos précédentes"],
      axis: ["Ouverture des ventes", "Soirée"],
      stats: [
        { v: "842", l: "places vendues" },
        { v: "+5 %", l: "vs la soirée du 12 sept." },
        { v: "38 %", l: "de nouveaux" },
      ],
      send: "E-mail « Line-up »",
    },
    envois: {
      title: "Automatisations",
      body: "Bienvenue, retour après une absence, rappel la veille : réglées une fois, envoyées toujours. Pause à tout moment.",
      flow: [
        { k: "Déclencheur", v: "Premier achat chez vous" },
        { k: "Attendre", v: "1 jour après la soirée" },
        { k: "E-mail", v: "« Merci d’être venu(e) »" },
      ],
    },
  },
  pricing: {
    eyebrow: "Tarif",
    title: "Un seul prix. Tout l’outil inclus.",
    accent: "inclus",
    sub: "Un petit abonnement fixe. Ensuite, vous ne payez que ce que vous envoyez.",
    monthly: "Mensuel",
    annual: "Annuel",
    annualNote: "Annuel : **30 000 Yunits offerts d’un coup**, soit environ deux mois offerts.",
    plan: "Yuno CRM",
    launch: "Prix de lancement",
    month: 29,
    year: 348,
    perMonth: "HT / mois",
    perYear: "HT / an",
    subMonthly:
      "Puis 39 € pour les nouveaux clients. Vous, vous gardez 29 € tant que vous restez abonné.",
    subAnnual: "Soit 29 € par mois, sans remise. Facturé une fois par an.",
    monthlyYunits: "**10 000 Yunits** offerts chaque mois",
    monthlyYunitsSub: "de quoi envoyer 10 000 e-mails",
    annualBonus: "**30 000 Yunits** en plus, d’un coup",
    annualBonusSub: "≈ 60 € d’envois",
    cta: "Essayer 14 jours gratuitement",
    notes: ["Sans carte bancaire", "5 000 Yunits offerts pendant l’essai"],
    includedTitle: "Tout est inclus",
    includedSub: "Rien à débloquer, aucune option.",
    feats: [
      { t: "Connexion Shotgun", d: "vos ventes arrivent toutes seules" },
      { t: "Fichier clients", d: "un seul fichier pour toutes vos soirées" },
      { t: "Segments", d: "habitués, nouveaux, à relancer" },
      { t: "Bilans de soirée", d: "ce qui a marché, soirée par soirée" },
      { t: "Campagnes e-mail", d: "et SMS, au même endroit" },
      { t: "Automatisations", d: "bienvenue, relances, rappels" },
      { t: "Audiences Meta", d: "vos segments en publicités · bientôt" },
      { t: "Assistant IA", d: "gratuit, sans compter" },
      { t: "Votre IA par le MCP", d: "ChatGPT, Claude, Gemini" },
      { t: "Équipe sans limite", d: "aucun siège à payer" },
    ],
    vat: "Prix hors taxes. TVA 20 % ajoutée à la facture.",
    yunits: {
      eyebrow: "Les Yunits",
      title: "Qu’est-ce qu’un Yunit ?",
      soon: "Bientôt",
      rates: [
        { name: "E-mail", cost: 1, soon: false },
        { name: "SMS", cost: 40, soon: false },
        { name: "DM Instagram", cost: 10, soon: true },
        { name: "WhatsApp", cost: 100, soon: true },
      ],
      accent: "Yunit",
      sub: "La monnaie de l’outil. Chaque envoi en consomme quelques-uns, et 10 000 sont offerts chaque mois avec votre abonnement.",
      free: "Toujours gratuits",
      freeItems: [
        "Les tests d’envoi",
        "L’assistant IA",
        "Les contacts que Yuno écarte pour ne pas les saturer",
      ],
      eq: "10 000 Yunits, c’est 10 000 e-mails, ou 250 SMS, ou un mélange des deux.",
      wallet: "Votre solde",
      chip: ["Offerts + achetés", "Solde bas", "Rechargé"],
      rows: [
        { t: "Campagne « Samedi »", s: "2 200 e-mails", d: "− 2 200", k: "minus" },
        { t: "Relance SMS", s: "60 contacts", d: "− 2 400", k: "minus" },
        { t: "Test d’envoi", s: "envoyé à vous-même", d: "Gratuit", k: "free" },
        { t: "Assistant IA", s: "12 questions posées", d: "Gratuit", k: "free" },
        { t: "Campagne « Brunch »", s: "5 000 e-mails", d: "− 5 000", k: "minus" },
        { t: "Recharge de 10 €", s: "en un clic", d: "+ 5 000", k: "plus" },
      ],
    },
    sim: {
      title: "Combien me coûtera mon mois ?",
      sub: "Choisissez un profil ou réglez vos envois. Le calcul utilise les vraies recharges, au meilleur prix.",
      presets: [
        { id: "asso", label: "Petite structure", desc: "4 000 e-mails", e: 4000, s: 0 },
        {
          id: "orga",
          label: "Organisateur hebdo",
          desc: "45 000 e-mails · 300 SMS",
          e: 45000,
          s: 300,
        },
        { id: "club", label: "Club actif", desc: "90 000 e-mails · 500 SMS", e: 90000, s: 500 },
      ],
      emails: "E-mails par mois",
      sms: "SMS par mois",
      estimate: "Estimation · par mois",
      subscription: "Abonnement",
      sends: "Vos envois",
      included: "Offerts avec l’abonnement",
      recharges: "Recharges",
      enough: "Vos Yunits offerts suffisent : aucune recharge.",
      left: "Il vous reste {n} Yunits après ce mois, valables un an.",
      exact: "Pile ce qu’il faut.",
      offered: "Offerts",
      bought: "Rechargés",
    },
  },
  faq: {
    eyebrow: "FAQ",
    title: "Questions fréquentes.",
    accent: "fréquentes",
    sub: "Une autre question ? Écrivez-nous, on répond le jour même.",
    email: "contact@yunoapp.eu",
    items: [
      {
        q: "Yuno modifie-t-il quelque chose chez Shotgun ?",
        a: "Non. Yuno ne fait que lire : il ne crée, ne rembourse, ne scanne et ne publie rien. Vous pouvez couper la connexion à tout moment, depuis Yuno ou depuis Shotgun.",
      },
      {
        q: "Dois-je donner mon mot de passe ?",
        a: "Non. Vous générez un jeton dans les intégrations de Shotgun et vous le collez dans Yuno avec votre ID organisateur. Il ne sert qu’à lire vos données et s’efface quand vous déconnectez.",
      },
      {
        q: "Combien de temps avant de voir mes clients ?",
        a: "La connexion prend environ 2 minutes. Yuno importe ensuite tout votre historique (soirées, billets, acheteurs) et vos clients apparaissent classés par fidélité.",
      },
      {
        q: "Puis-je écrire à tous mes acheteurs ?",
        a: "Seuls ceux qui ont accepté de recevoir vos e-mails reçoivent vos messages. Les autres comptent dans vos chiffres, sans rien recevoir. Chaque message propose aussi une désinscription.",
      },
      {
        q: "Yuno lit-il mes statistiques Instagram ?",
        a: "Non, Yuno n’a aucun accès aux données Instagram. Il mesure ce qui passe chez lui : vos ventes Shotgun, vos e-mails et SMS, les clics sur vos liens Yuno.",
      },
      {
        q: "Puis-je brancher ChatGPT, Claude ou Gemini ?",
        a: "Oui, par le MCP de Yuno. Vous connectez votre IA en quelques clics, puis vous lui posez vos questions sur vos clients, vos soirées et vos envois : elle répond avec vos vrais chiffres. Vous pouvez couper l’accès à tout moment.",
      },
      {
        q: "Et si je n’utilise pas Shotgun ?",
        a: "Aujourd’hui, la connexion automatique est celle de Shotgun. Depuis n’importe quel autre outil, importez votre fichier clients (CSV ou Excel) : il rejoint la même base, sans doublons.",
      },
      {
        q: "Combien ça coûte, et après les 14 jours ?",
        a: "29 € HT par mois, avec 10 000 Yunits offerts chaque mois pour vos envois. Sans abonnement à la fin de l’essai, le compte se met en pause : vous voyez toujours votre base, rien ne part.",
      },
      {
        q: "Que se passe-t-il s’il me manque des Yunits ?",
        a: "Avant chaque envoi, Yuno affiche son coût et votre solde. S’il en manque, vous rechargez sans quitter l’écran et l’envoi reprend. Les offerts partent en premier, ceux achetés restent valables un an.",
      },
      {
        q: "Le prix de 29 € peut-il augmenter ?",
        a: "Le prix passera à 39 € plus tard, pour les nouveaux clients seulement. Si vous vous abonnez à 29 €, vous gardez ce prix tant que vous restez abonné.",
      },
      {
        q: "Où sont hébergées mes données ?",
        a: "En Europe. Vous pouvez à tout moment exporter vos clients ou tout supprimer, sans rien changer chez Shotgun.",
      },
    ],
  },
  final: {
    title: "Votre prochaine soirée se vend déjà. Sachez qui vient.",
    accent: "qui vient",
    sub: "Connectez Shotgun en 2 minutes et retrouvez tous vos clients. 14 jours d’essai, sans carte bancaire.",
    cta: "Essayer 14 jours gratuitement",
  },
  footer: {
    tagline: "Le fichier clients des clubs et organisateurs de soirées.",
    cols: [
      {
        title: "Produit",
        links: [
          { label: "Fonctionnalités", href: "#fonctionnalites" },
          { label: "Comment ça marche", href: "#etapes" },
          { label: "Tarifs", href: "#tarifs" },
        ],
      },
      {
        title: "Aide",
        links: [
          { label: "FAQ", href: "#faq" },
          { label: "Parler au fondateur", href: "whatsapp" },
          { label: "Se connecter", href: "login" },
        ],
      },
      {
        title: "Légal",
        links: [
          { label: "CGU", href: "/fr/terms" },
          { label: "Confidentialité", href: "/fr/privacy" },
        ],
      },
    ],
    region: "Données hébergées en Europe",
    rights: "Yuno",
    suite: "Vous voulez aussi vendre vos billets ? Découvrez Yuno Billetterie",
  },
  mobileCta: "Essayer 14 jours gratuitement",
  signup: {
    roleTitle: "Qui branche sa billetterie ?",
    roles: [
      { id: "club", label: "Un club ou une salle", hint: "Vos soirées et vos habitués" },
      { id: "organizer", label: "Des soirées", hint: "Organisateur ou collectif" },
      { id: "promoter", label: "Une équipe de promo", hint: "Promoteur ou agence" },
      { id: "other", label: "Autre chose", hint: "Festival, bar, DJ…" },
    ],
    roleSub: "Yuno CRM prépare votre console en conséquence — deux minutes, sans appel.",
    structureSub: "Votre console et vos premiers bilans se construisent là-dessus.",
    tool: "Votre billetterie",
    toolHint:
      "Shotgun se connecte directement ; pour les autres, vous importerez votre fichier clients.",
  },
};

export type CrmContent = typeof fr;

const en: CrmContent = {
  meta: {
    title: "Yuno CRM — Know who comes to your nights, and bring them back",
    description:
      "Yuno CRM plugs into Shotgun and gathers your buyers in one customer file: regulars, newcomers, people to win back. Emails, SMS, night reports. €29 excl. VAT a month, 14-day trial, no card.",
  },
  whatsappMessage: "Hi Paul 👋 I sell on Shotgun and I'd like to know more about Yuno CRM.",
  nav: {
    links: [
      { label: "Features", href: "#fonctionnalites" },
      { label: "How it works", href: "#etapes" },
      { label: "Pricing", href: "#tarifs" },
      { label: "FAQ", href: "#faq" },
    ],
    cta: "Try 14 days",
    login: "Log in",
    menu: "Menu",
    close: "Close",
  },
  hero: {
    eyebrowTag: "Yuno CRM",
    eyebrow: "Plugged into Shotgun in 2 minutes",
    title: "Know who comes to your nights. And bring them back.",
    accent: "back",
    sub: "Yuno gathers all your Shotgun buyers in one customer file, then helps you find them, write to them by email and SMS, and see what fills your room.",
    cta: "Try it free for 14 days",
    trust: ["Connected through the Shotgun API", "Ready in 2 minutes", "No card needed"],
    frameUrl: "yunoapp.eu/crm",
    live: "Live",
    toasts: [
      { title: "Camille is back for the 4th time", sub: "Regular · Techno Night" },
      { title: "“Last call” scheduled for 6 pm", sub: "6,120 contacts · 6,120 Yunits" },
      { title: "▲ 36 tickets today", sub: "Shotgun sync · 2 min ago" },
    ],
  },
  dash: {
    venue: "Le Bunker",
    venueSub: "Paris 11e · Club",
    nav: {
      groups: ["Run", "Act", "Know"],
      home: "Home",
      analyses: "Analytics",
      campaigns: "Campaigns",
      nights: "Nights",
      clients: "Customers",
      connectors: "Connectors",
      settings: "Settings",
      help: "Help",
      yunits: "Yunits",
      yunitsSub: "8,940 available",
    },
    search: "Search a customer, a campaign…",
    sync: "Shotgun synced · 6:38 pm",
    yunitsWord: "Yunits",
    date: "Saturday 3 October",
    hello: "Hello Nina",
    subtitle: "3 things to do today, one before 6 pm.",
    see: "See ↓",
    newCampaign: "New campaign",
    mission: {
      label: "Mission report · 30 Sept",
      title: "“Line-up Techno Night” brought 1,120 people to your page.",
      sub: "214 sign-ups and 61 purchases from those visits · 6,040 Yunits spent.",
      link: "See details",
    },
    sales: {
      title: "How much did I sell?",
      unit: "Sales per day, net of refunds",
      periods: [
        { k: "7 d", label: "last 7 days", vs: "the previous 7 days", tot: 11480, d: 0.08, n: 7 },
        {
          k: "30 d",
          label: "last 30 days",
          vs: "the previous 30 days",
          tot: 38940,
          d: 0.12,
          n: 30,
        },
        {
          k: "90 d",
          label: "last 90 days",
          vs: "the previous 90 days",
          tot: 104300,
          d: 0.05,
          n: 45,
        },
      ],
      moreSub: "That's {n} more",
      legend: ["Sales of the day", "Previous period", "Message sent"],
      insight:
        "In the 2 days after a send, you sell 2.4 times more on average than the rest of the time.",
      tipPrev: "Previous period: {n}",
      sends: [
        "Line-up Techno Night · email",
        "Warehouse presale · email",
        "Reminder to regulars · SMS",
      ],
    },
    kpis: [
      {
        label: "Customers",
        value: "18,420",
        delta: "▲ 36 today",
        note: "Unique contacts, duplicates merged",
      },
      {
        label: "Regulars",
        value: "2,140",
        delta: "▲ 12 this month",
        note: "Came 3 times or more · last 6 months",
      },
      {
        label: "Conversion rate",
        value: "9%",
        delta: "▲ 1.4 pt vs the previous send",
        note: "Bought within 48 h of “Line-up Techno Night”",
      },
      {
        label: "Reachable",
        value: "86%",
        delta: "15,880 of 18,420 customers",
        note: "Customers a message can reach",
      },
    ],
    reach: ["Email + SMS 71%", "None 14%"],
    night: {
      label: "Next night",
      when: "Tonight · 11 pm",
      name: "Techno Night",
      place: "Le Bunker · Saturday 3 October",
      of: "of 1,000 spots",
      today: "▲ 36 today",
      axis: ["26 Sept", "Tonight"],
      legend: ["This night", "Techno Night, 12 Sept", "Lead"],
      insight:
        "You're **5% ahead** of your last night at the same point. At this pace: **about 960** spots tonight.",
    },
    who: {
      title: "Who's buying?",
      sub: "The 842 buyers of Techno Night",
      center: "buyers",
      rows: [
        { l: "Regulars", sub: "Came 3 times or more", n: 236, p: 28 },
        { l: "Occasional", sub: "Fewer than 3 nights", n: 286, p: 34 },
        { l: "Newcomers", sub: "Their 1st night", n: 320, p: 38 },
      ],
      buyers: "buyers",
      note: "Almost 4 buyers in 10 are **new**: now's the time to give them a reason to come back.",
      link: "Prepare a welcome message",
    },
    todo: {
      title: "What needs doing today?",
      items: [
        {
          badge: "Today",
          title: "Nudge 214 regulars without a ticket",
          why: "Came 3 times or more, reachable. The night is tonight.",
          cta: "Prepare the nudge",
          primary: true,
        },
        {
          badge: "Before 6 pm",
          title: "Approve “Last call — Techno Night”",
          why: "Draft complete, scheduled at 6 pm for 6,120 contacts.",
          cta: "Review and approve",
          primary: false,
        },
        {
          badge: "This week",
          title: "Plan a Yunits top-up",
          why: "After 6 pm, 2,820 Yunits will be left: enough for emails, not for an SMS to everyone.",
          cta: "Top up",
          primary: false,
        },
      ],
    },
  },
  proof: {
    line: "Every Shotgun buyer becomes a profile. With their history, their loyalty, and a good reason to write to them.",
    pills: [
      {
        ini: "CR",
        name: "Camille R.",
        meta: "7 nights · seen 14 Sept",
        tag: "Regular",
        tone: "hot",
      },
      { ini: "YB", name: "Yanis B.", meta: "4 nights · seen 7 Sept", tag: "Regular", tone: "hot" },
      { ini: "IM", name: "Inès M.", meta: "1st night · yesterday", tag: "New", tone: "new" },
      {
        ini: "LD",
        name: "Lucas D.",
        meta: "3 nights · 5 months ago",
        tag: "Win back",
        tone: "cold",
      },
      {
        ini: "SD",
        name: "Sarah D.",
        meta: "11 nights · seen Saturday",
        tag: "Regular",
        tone: "hot",
      },
      {
        ini: "HM",
        name: "Hugo M.",
        meta: "2 nights · seen 30 Aug",
        tag: "Occasional",
        tone: "warm",
      },
      { ini: "NK", name: "Nora K.", meta: "1st night · Techno Night", tag: "New", tone: "new" },
      {
        ini: "TG",
        name: "Théo G.",
        meta: "5 nights · 3 months ago",
        tag: "Win back",
        tone: "cold",
      },
      { ini: "LP", name: "Léa P.", meta: "9 nights · seen 26 Sept", tag: "Regular", tone: "hot" },
      {
        ini: "AB",
        name: "Adam B.",
        meta: "2 nights · seen 12 Sept",
        tag: "Occasional",
        tone: "warm",
      },
    ] as Pill[],
    connected: "Connected to your Shotgun account",
    facts: [
      {
        title: "Your whole history",
        body: "Nights, tickets and buyers imported as soon as you connect.",
      },
      { title: "Always up to date", body: "Every new ticket lands in your file on its own." },
      { title: "Read-only", body: "Yuno never edits, refunds or publishes anything on Shotgun." },
    ],
  },
  problem: {
    eyebrow: "The problem",
    title: "Your next regular has already come 3 times. You just don't know who they are.",
    accent: "who they are",
    sub: "Ticketing tells you how many tickets went. Not who comes back, who disappeared, or who to nudge.",
    cards: [
      {
        title: "Your sales tell you nothing about your customers.",
        body: "How many visits before they buy, where they came from, where they drop off: Yuno shows the journey, not just the ticket.",
      },
      {
        title: "The same email for everyone. Nobody clicks.",
        body: "Yuno tailors emails and SMS to each customer, boosted by AI and automations.",
      },
    ],
  },
  night: {
    title: "Your tickets already know who comes back. Now you do too.",
    accent: "you do too",
    sub: "Every ticket leaves a name, a date, a night. Yuno brings it all into one file, merges duplicates and ranks your customers by loyalty. It updates itself.",
    table: {
      title: "All customers",
      sub: "18,420 unique contacts · ranked by loyalty",
      search: "Search a customer",
      filters: ["All", "Regulars", "New", "Win back"],
      export: "Export",
      cols: ["Customer", "Nights", "Last visit", "Loyalty", "Reachable", "Status"],
      rows: [
        {
          ini: "SD",
          name: "Sarah Dubois",
          sub: "Paris 11e",
          nights: 11,
          last: "3 Oct",
          score: 98,
          reach: "Email · SMS",
          tag: "Regular",
          tone: "hot",
        },
        {
          ini: "CL",
          name: "Camille Laurent",
          sub: "Montreuil",
          nights: 14,
          last: "26 Sept",
          score: 96,
          reach: "Email · SMS",
          tag: "Regular",
          tone: "hot",
        },
        {
          ini: "LP",
          name: "Léa Petit",
          sub: "Paris 20e",
          nights: 9,
          last: "26 Sept",
          score: 91,
          reach: "Email",
          tag: "Regular",
          tone: "hot",
        },
        {
          ini: "HM",
          name: "Hugo Marchand",
          sub: "Paris 18e",
          nights: 9,
          last: "12 Sept",
          score: 88,
          reach: "Email · SMS",
          tag: "Regular",
          tone: "hot",
        },
        {
          ini: "TG",
          name: "Théo Garnier",
          sub: "Vincennes",
          nights: 5,
          last: "4 Jul",
          score: 64,
          reach: "Email",
          tag: "Win back",
          tone: "cold",
        },
        {
          ini: "AB",
          name: "Adam Benali",
          sub: "Paris 10e",
          nights: 2,
          last: "12 Sept",
          score: 41,
          reach: "SMS",
          tag: "Occasional",
          tone: "warm",
        },
        {
          ini: "NK",
          name: "Nora Kaci",
          sub: "Saint-Ouen",
          nights: 1,
          last: "3 Oct",
          score: 22,
          reach: "Email · SMS",
          tag: "New",
          tone: "new",
        },
        {
          ini: "YH",
          name: "Yanis Haddad",
          sub: "Paris 13e",
          nights: 1,
          last: "3 Oct",
          score: 20,
          reach: "Email",
          tag: "New",
          tone: "new",
        },
      ],
    },
    chipsTitle: "Never let anyone slip away",
    chips: [
      [
        "Regulars",
        "Newcomers",
        "Win back",
        "Big spenders",
        "Duplicates merged",
        "One profile per customer",
        "CSV or Excel import",
        "Find anyone in 2 seconds",
      ],
      [
        "Night report",
        "Compared with the last night",
        "Who's buying",
        "Sales pace",
        "Sales after a send",
        "Next night",
        "Export anytime",
      ],
      [
        "Email campaigns",
        "SMS",
        "Ready-made templates",
        "Scheduled sends",
        "Cost shown before sending",
        "Unsubscribes handled",
        "Unlimited team",
        "MCP · ChatGPT, Claude, Gemini",
        "Meta audiences · soon",
      ],
    ],
    cta: "Connect my Shotgun account",
  },
  steps: {
    eyebrow: "How it works",
    title: "Yuno in 2 minutes.",
    accent: "2 minutes",
    sub: "You connect, Yuno sorts everything. Nothing to type: your customers are ready before your coffee is finished.",
    cta: "Connect my Shotgun account",
    stepWord: "Step",
    items: [
      {
        title: "Connect Shotgun.",
        body: "Paste your organizer ID and your API token, generated in your Shotgun integrations. No password.",
      },
      {
        title: "Yuno sorts it all.",
        body: "Nights, tickets and buyers are imported, grouped by person and ranked by loyalty. Then everything stays in sync on its own.",
      },
      {
        title: "Open. See. Follow up.",
        body: "Every morning: what sold, who to nudge, what needs your attention. You stop analysing, you act.",
      },
    ],
    connect: {
      title: "Connect Shotgun",
      sub: "Read-only. Nothing changes on Shotgun.",
      id: "Organizer ID",
      idVal: "48213",
      token: "API token",
      help: "Where do I find my token?",
      btn: "Connect",
      busy: "Checking…",
      ok: "Connected · syncs every 15 min",
    },
    sort: {
      title: "Importing your history",
      sub: "Yuno sorts your customers, you have nothing to do.",
      rows: [
        { label: "Nights imported", n: 38 },
        { label: "Tickets imported", n: 24812 },
        { label: "Customers grouped", n: 18420 },
        { label: "Duplicates merged", n: 3106 },
      ],
      done: "Shotgun history imported",
    },
  },
  channels: {
    eyebrow: "Sending",
    title: "Your customers. Your messages. One counter.",
    accent: "counter",
    sub: "Write to the right segment by email or SMS, see the cost before you send, schedule it. Email and SMS today, Instagram and WhatsApp tomorrow: same place, same counter.",
    cta: "Try it free for 14 days",
    composer: {
      title: "New message",
      to: "To",
      cost: "Cost",
      after: "Balance after sending",
      schedule: "Saturday · 6 pm",
      send: "Schedule",
      subject: "Subject",
      messages: [
        {
          seg: "Regulars",
          count: 1284,
          channel: "Email",
          subject: "Saturday, we go again.",
          text: "Three nights in a row now. Your spot is waiting on Saturday, before everyone else.",
        },
        {
          seg: "Newcomers",
          count: 320,
          channel: "SMS",
          subject: "",
          text: "Thanks for coming to Techno Night! Next date on the 17th: yuno.fr/bunker",
        },
        {
          seg: "Dormant",
          count: 740,
          channel: "Email",
          subject: "We kept you a spot.",
          text: "It's been a while. Warehouse Sessions, Friday 9th: the presale opens for you first.",
        },
      ],
      balance: 8940,
    },
    rates: [
      { name: "Email", cost: "1 Yunit", soon: false },
      { name: "SMS", cost: "40 Yunits", soon: false },
      { name: "Instagram DM", cost: "Soon", soon: true },
      { name: "WhatsApp", cost: "Soon", soon: true },
    ],
    footnote:
      "Test sends are free. Yuno sets aside contacts that already got too many messages, and doesn't count them.",
  },
  mcp: {
    eyebrow: "Integrations",
    title: "Your data. Your AI. Through MCP.",
    accent: "MCP",
    sub: "Connect Yuno to ChatGPT, Claude, Gemini and more to turn your customers and your sales into instant analysis.",
    cta: "Try it free for 14 days",
    stage: "AI working for your nights",
    stageAccent: "your nights",
    placeholder: "What do you want to know about your customers?",
    models: ["Claude", "ChatGPT", "Gemini"],
    via: "through the Yuno MCP",
    convo: [
      {
        q: "Which regulars haven't come back in 2 months?",
        a: "214 regulars haven't bought anything in 60 days, 168 of them reachable by email. Shall I prepare the “Win back” segment?",
      },
      {
        q: "Which night brought the most newcomers in September?",
        a: "Techno Night on 12 Sept: 312 new customers, 39% of buyers. Warehouse Sessions follows with 204.",
      },
      {
        q: "Is Techno Night selling ahead of the last one?",
        a: "Yes: 842 spots tonight vs 802 at the same point on 12 Sept, a 5% lead. At this pace, about 960 spots.",
      },
    ],
    chips: ["Analyse", "Segment", "Write", "Compare", "Forecast"],
  },
  compare: {
    title:
      "Your ticketing tells you how many tickets went. Yuno tells you who to nudge to fill the next one.",
    accent: "who to nudge to fill the next one",
    tabs: ["Your ticketing gives you", "Yuno gives you"],
    left: {
      title: "What your ticketing gives you",
      items: [
        "A ticket total per night",
        "An export to reopen every time",
        "The same people in ten files",
        "No idea who comes back",
      ],
    },
    right: {
      title: "What Yuno gives you",
      items: [
        "Who comes back, and how often",
        "One profile per person, for good",
        "The regulars drifting away",
        "Segments ready for a message",
        "The report of every night",
      ],
    },
    cta: "Try it free for 14 days",
  },
  bento: {
    eyebrow: "Features",
    title: "Everything your ticketing doesn't show you.",
    accent: "doesn't show you",
    sub: "A tool built for one thing: turning your buyers into regulars.",
    cta: "Try it free for 14 days",
    clients: {
      title: "Customer file",
      body: "Every buyer becomes a profile, with all their nights. Duplicates merged, anyone found in 2 seconds.",
      search: "Search a customer",
    },
    segments: {
      title: "Segments",
      body: "Regulars, newcomers, dormant: everyone in the right list. The lists update themselves.",
      rows: [
        { l: "Regulars", n: 1284, w: 100 },
        { l: "Newcomers", n: 962, w: 75 },
        { l: "Dormant", n: 740, w: 58 },
        { l: "Big spenders", n: 118, w: 14 },
      ],
      action: "Write to the dormant ones",
    },
    relance: {
      title: "Regulars to win back",
      body: "Yuno spots the ones drifting away and hands you the list. Every message goes to someone who already knows your nights.",
      list: "To win back · 214",
    },
    bilans: {
      title: "Night reports",
      body: "Every night compared with the previous one at the same point. You finally know which message sold.",
      legend: ["This night", "Your previous ones"],
      axis: ["Sales open", "Night"],
      stats: [
        { v: "842", l: "spots sold" },
        { v: "+5%", l: "vs the 12 Sept night" },
        { v: "38%", l: "newcomers" },
      ],
      send: "“Line-up” email",
    },
    envois: {
      title: "Automations",
      body: "Welcome, back after a break, reminder the day before: set once, sent forever. Pause anytime.",
      flow: [
        { k: "Trigger", v: "First purchase with you" },
        { k: "Wait", v: "1 day after the night" },
        { k: "Email", v: "“Thanks for coming”" },
      ],
    },
  },
  pricing: {
    eyebrow: "Pricing",
    title: "One price. The whole tool included.",
    accent: "included",
    sub: "A small fixed subscription. After that, you only pay for what you send.",
    monthly: "Monthly",
    annual: "Yearly",
    annualNote: "Yearly: **30,000 Yunits offered at once**, about two months free.",
    plan: "Yuno CRM",
    launch: "Launch price",
    month: 29,
    year: 348,
    perMonth: "excl. VAT / month",
    perYear: "excl. VAT / year",
    subMonthly: "Then €39 for new customers. You keep €29 for as long as you stay subscribed.",
    subAnnual: "That's €29 a month, no discount. Billed once a year.",
    monthlyYunits: "**10,000 Yunits** offered every month",
    monthlyYunitsSub: "enough to send 10,000 emails",
    annualBonus: "**30,000 Yunits** on top, at once",
    annualBonusSub: "≈ €60 of sends",
    cta: "Try it free for 14 days",
    notes: ["No card needed", "5,000 Yunits offered during the trial"],
    includedTitle: "Everything included",
    includedSub: "Nothing to unlock, no add-ons.",
    feats: [
      { t: "Shotgun connection", d: "your sales come in on their own" },
      { t: "Customer file", d: "one file for all your nights" },
      { t: "Segments", d: "regulars, newcomers, win back" },
      { t: "Night reports", d: "what worked, night by night" },
      { t: "Email campaigns", d: "and SMS, in the same place" },
      { t: "Automations", d: "welcome, follow-ups, reminders" },
      { t: "Meta audiences", d: "your segments as ads · soon" },
      { t: "AI assistant", d: "free, no counting" },
      { t: "Your AI through MCP", d: "ChatGPT, Claude, Gemini" },
      { t: "Unlimited team", d: "no seats to pay for" },
    ],
    vat: "Prices excl. VAT. VAT added on the invoice.",
    yunits: {
      eyebrow: "Yunits",
      title: "What's a Yunit?",
      soon: "Soon",
      rates: [
        { name: "Email", cost: 1, soon: false },
        { name: "SMS", cost: 40, soon: false },
        { name: "Instagram DM", cost: 10, soon: true },
        { name: "WhatsApp", cost: 100, soon: true },
      ],
      accent: "Yunit",
      sub: "The tool's currency. Each send uses a few, and 10,000 are offered every month with your subscription.",
      free: "Always free",
      freeItems: [
        "Test sends",
        "The AI assistant",
        "Contacts Yuno sets aside so as not to overload them",
      ],
      eq: "10,000 Yunits means 10,000 emails, or 250 SMS, or a mix of both.",
      wallet: "Your balance",
      chip: ["Offered + bought", "Low balance", "Topped up"],
      rows: [
        { t: "“Saturday” campaign", s: "2,200 emails", d: "− 2,200", k: "minus" },
        { t: "SMS follow-up", s: "60 contacts", d: "− 2,400", k: "minus" },
        { t: "Test send", s: "sent to yourself", d: "Free", k: "free" },
        { t: "AI assistant", s: "12 questions asked", d: "Free", k: "free" },
        { t: "“Brunch” campaign", s: "5,000 emails", d: "− 5,000", k: "minus" },
        { t: "€10 top-up", s: "in one click", d: "+ 5,000", k: "plus" },
      ],
    },
    sim: {
      title: "How much will my month cost?",
      sub: "Pick a profile or set your sends. The maths uses the real top-ups, at the best price.",
      presets: [
        { id: "asso", label: "Small team", desc: "4,000 emails", e: 4000, s: 0 },
        {
          id: "orga",
          label: "Weekly organizer",
          desc: "45,000 emails · 300 SMS",
          e: 45000,
          s: 300,
        },
        { id: "club", label: "Busy club", desc: "90,000 emails · 500 SMS", e: 90000, s: 500 },
      ],
      emails: "Emails per month",
      sms: "SMS per month",
      estimate: "Estimate · per month",
      subscription: "Subscription",
      sends: "Your sends",
      included: "Offered with the subscription",
      recharges: "Top-ups",
      enough: "Your offered Yunits are enough: no top-up.",
      left: "You'll have {n} Yunits left after this month, valid for a year.",
      exact: "Exactly what you need.",
      offered: "Offered",
      bought: "Topped up",
    },
  },
  faq: {
    eyebrow: "FAQ",
    title: "Frequently asked questions.",
    accent: "questions",
    sub: "Another question? Write to us, we answer the same day.",
    email: "contact@yunoapp.eu",
    items: [
      {
        q: "Does Yuno change anything on Shotgun?",
        a: "No. Yuno only reads: it never creates, refunds, scans or publishes anything. You can cut the connection anytime, from Yuno or from Shotgun.",
      },
      {
        q: "Do I have to give my password?",
        a: "No. You generate a token in your Shotgun integrations and paste it into Yuno with your organizer ID. It only reads your data and is deleted when you disconnect.",
      },
      {
        q: "How long before I see my customers?",
        a: "Connecting takes about 2 minutes. Yuno then imports your whole history (nights, tickets, buyers) and your customers show up ranked by loyalty.",
      },
      {
        q: "Can I write to all my buyers?",
        a: "Only people who agreed to receive your emails get your messages. The others count in your numbers but receive nothing. Every message also offers an unsubscribe link.",
      },
      {
        q: "Does Yuno read my Instagram stats?",
        a: "No, Yuno has no access to Instagram data. It measures what goes through it: your Shotgun sales, your emails and SMS, the clicks on your Yuno links.",
      },
      {
        q: "Can I plug in ChatGPT, Claude or Gemini?",
        a: "Yes, through the Yuno MCP. You connect your AI in a few clicks, then ask it about your customers, your nights and your sends: it answers with your real numbers. You can cut the access anytime.",
      },
      {
        q: "What if I don't use Shotgun?",
        a: "Today, the automatic connection is Shotgun's. From any other tool, import your customer file (CSV or Excel): it joins the same base, without duplicates.",
      },
      {
        q: "How much is it, and after the 14 days?",
        a: "€29 excl. VAT a month, with 10,000 Yunits offered every month for your sends. Without a subscription at the end of the trial, the account pauses: you still see your base, nothing goes out.",
      },
      {
        q: "What if I run out of Yunits?",
        a: "Before every send, Yuno shows its cost and your balance. If some are missing, you top up without leaving the screen and the send resumes. Offered Yunits go first; the ones you buy stay valid for a year.",
      },
      {
        q: "Can the €29 price go up?",
        a: "The price will move to €39 later, for new customers only. If you subscribe at €29, you keep that price for as long as you stay subscribed.",
      },
      {
        q: "Where is my data hosted?",
        a: "In Europe. You can export your customers or delete everything at any time, without changing anything on Shotgun.",
      },
    ],
  },
  final: {
    title: "Your next night is already selling. Know who's coming.",
    accent: "who's coming",
    sub: "Connect Shotgun in 2 minutes and find all your customers. 14-day trial, no card needed.",
    cta: "Try it free for 14 days",
  },
  footer: {
    tagline: "The customer file for clubs and night organizers.",
    cols: [
      {
        title: "Product",
        links: [
          { label: "Features", href: "#fonctionnalites" },
          { label: "How it works", href: "#etapes" },
          { label: "Pricing", href: "#tarifs" },
        ],
      },
      {
        title: "Help",
        links: [
          { label: "FAQ", href: "#faq" },
          { label: "Talk to the founder", href: "whatsapp" },
          { label: "Log in", href: "login" },
        ],
      },
      {
        title: "Legal",
        links: [
          { label: "Terms", href: "/terms" },
          { label: "Privacy", href: "/privacy" },
        ],
      },
    ],
    region: "Data hosted in Europe",
    rights: "Yuno",
    suite: "Want to sell your tickets too? Discover Yuno Ticketing",
  },
  mobileCta: "Try it free for 14 days",
  signup: {
    roleTitle: "Who's plugging in their ticketing?",
    roles: [
      { id: "club", label: "A club or venue", hint: "Your nights and your regulars" },
      { id: "organizer", label: "Events & nights", hint: "Organizer or collective" },
      { id: "promoter", label: "A promoter team", hint: "Promoter or agency" },
      { id: "other", label: "Something else", hint: "Festival, bar, DJ…" },
    ],
    roleSub: "Yuno CRM sets up your console for it — two minutes, no call needed.",
    structureSub: "Your console and your first reports are built on it.",
    tool: "Your ticketing",
    toolHint: "Shotgun connects directly; for the others, you'll import your customer file.",
  },
};

const es: CrmContent = {
  meta: {
    title: "Yuno CRM — Sabe quién viene a tus fiestas, y haz que vuelvan",
    description:
      "Yuno CRM se conecta a Shotgun y reúne a tus compradores en un solo archivo de clientes: habituales, nuevos, a recuperar. E-mails, SMS, informes de cada fiesta. 29 € + IVA al mes, 14 días de prueba sin tarjeta.",
  },
  whatsappMessage: "Hola Paul 👋 Vendo en Shotgun y me gustaría saber más sobre Yuno CRM.",
  nav: {
    links: [
      { label: "Funciones", href: "#fonctionnalites" },
      { label: "Cómo funciona", href: "#etapes" },
      { label: "Precios", href: "#tarifs" },
      { label: "FAQ", href: "#faq" },
    ],
    cta: "Probar 14 días",
    login: "Entrar",
    menu: "Menú",
    close: "Cerrar",
  },
  hero: {
    eyebrowTag: "Yuno CRM",
    eyebrow: "Conectado a Shotgun en 2 minutos",
    title: "Sabe quién viene a tus fiestas. Y haz que vuelvan.",
    accent: "vuelvan",
    sub: "Yuno reúne a todos tus compradores de Shotgun en un solo archivo de clientes, y te ayuda a encontrarlos, a escribirles por e-mail y SMS, y a ver qué llena tu sala.",
    cta: "Probar gratis 14 días",
    trust: ["Conexión por la API de Shotgun", "Listo en 2 minutos", "Sin tarjeta"],
    frameUrl: "yunoapp.eu/crm",
    live: "En directo",
    toasts: [
      { title: "Camille vuelve por 4ª vez", sub: "Habitual · Techno Night" },
      { title: "«Last call» programado a las 18:00", sub: "6.120 contactos · 6.120 Yunits" },
      { title: "▲ 36 entradas hoy", sub: "Sincro Shotgun · hace 2 min" },
    ],
  },
  dash: {
    venue: "Le Bunker",
    venueSub: "París 11e · Club",
    nav: {
      groups: ["Pilotar", "Actuar", "Conocer"],
      home: "Inicio",
      analyses: "Análisis",
      campaigns: "Campañas",
      nights: "Fiestas",
      clients: "Clientes",
      connectors: "Conectores",
      settings: "Ajustes",
      help: "Ayuda",
      yunits: "Yunits",
      yunitsSub: "8.940 disponibles",
    },
    search: "Buscar un cliente, una campaña…",
    sync: "Shotgun sincronizado · 18:38",
    yunitsWord: "Yunits",
    date: "Sábado 3 de octubre",
    hello: "Hola Nina",
    subtitle: "3 acciones para hoy, una antes de las 18:00.",
    see: "Ver ↓",
    newCampaign: "Nueva campaña",
    mission: {
      label: "Informe de misión · 30 sept.",
      title: "«Line-up Techno Night» trajo a 1.120 personas a tu página.",
      sub: "214 inscripciones y 61 compras desde esas visitas · 6.040 Yunits gastados.",
      link: "Ver el detalle",
    },
    sales: {
      title: "¿Cuánto he vendido?",
      unit: "Ventas por día, sin reembolsos",
      periods: [
        {
          k: "7 d",
          label: "últimos 7 días",
          vs: "los 7 días anteriores",
          tot: 11480,
          d: 0.08,
          n: 7,
        },
        {
          k: "30 d",
          label: "últimos 30 días",
          vs: "los 30 días anteriores",
          tot: 38940,
          d: 0.12,
          n: 30,
        },
        {
          k: "90 d",
          label: "últimos 90 días",
          vs: "los 90 días anteriores",
          tot: 104300,
          d: 0.05,
          n: 45,
        },
      ],
      moreSub: "{n} más",
      legend: ["Ventas del día", "Periodo anterior", "Envío de un mensaje"],
      insight:
        "En los 2 días siguientes a un envío, vendes de media 2,4 veces más que el resto del tiempo.",
      tipPrev: "Periodo anterior: {n}",
      sends: [
        "Line-up Techno Night · e-mail",
        "Preventa Warehouse · e-mail",
        "Recordatorio a habituales · SMS",
      ],
    },
    kpis: [
      {
        label: "Clientes",
        value: "18.420",
        delta: "▲ 36 hoy",
        note: "Contactos únicos, duplicados fusionados",
      },
      {
        label: "Habituales",
        value: "2140",
        delta: "▲ 12 este mes",
        note: "Vinieron 3 veces o más · últimos 6 meses",
      },
      {
        label: "Tasa de conversión",
        value: "9 %",
        delta: "▲ 1,4 pt vs el envío anterior",
        note: "Compraron en las 48 h tras «Line-up Techno Night»",
      },
      {
        label: "Contactables",
        value: "86 %",
        delta: "15.880 de 18.420 clientes",
        note: "Clientes a los que llega un mensaje",
      },
    ],
    reach: ["E-mail + SMS 71 %", "Ninguno 14 %"],
    night: {
      label: "Próxima fiesta",
      when: "Esta noche · 23:00",
      name: "Techno Night",
      place: "Le Bunker · sábado 3 de octubre",
      of: "de 1.000 plazas",
      today: "▲ 36 hoy",
      axis: ["26 sept.", "Esta noche"],
      legend: ["Esta fiesta", "Techno Night del 12 sept.", "Ventaja"],
      insight:
        "Vas **un 5 % por delante** de tu última fiesta en el mismo momento. A este ritmo: **unas 960** plazas esta noche.",
    },
    who: {
      title: "¿Quién compra?",
      sub: "Los 842 compradores de Techno Night",
      center: "compradores",
      rows: [
        { l: "Habituales", sub: "Vinieron 3 veces o más", n: 236, p: 28 },
        { l: "Ocasionales", sub: "Menos de 3 fiestas", n: 286, p: 34 },
        { l: "Nuevos", sub: "Su 1ª fiesta", n: 320, p: 38 },
      ],
      buyers: "compradores",
      note: "Casi 4 de cada 10 compradores son **nuevos**: es el momento de darles un motivo para volver.",
      link: "Preparar un mensaje de bienvenida",
    },
    todo: {
      title: "¿Qué hay que hacer hoy?",
      items: [
        {
          badge: "Hoy",
          title: "Avisar a 214 habituales sin entrada",
          why: "Vinieron 3 veces o más, contactables. La fiesta es esta noche.",
          cta: "Preparar el aviso",
          primary: true,
        },
        {
          badge: "Antes de las 18:00",
          title: "Validar «Last call — Techno Night»",
          why: "Borrador completo, previsto a las 18:00 para 6.120 contactos.",
          cta: "Revisar y validar",
          primary: false,
        },
        {
          badge: "Esta semana",
          title: "Prever una recarga de Yunits",
          why: "Tras las 18:00 quedarán 2820 Yunits: suficiente para e-mails, no para un SMS a todos.",
          cta: "Recargar",
          primary: false,
        },
      ],
    },
  },
  proof: {
    line: "Cada comprador de Shotgun se convierte en una ficha. Con su historial, su fidelidad y un buen motivo para escribirle.",
    pills: [
      {
        ini: "CR",
        name: "Camille R.",
        meta: "7 fiestas · vista el 14 sept.",
        tag: "Habitual",
        tone: "hot",
      },
      {
        ini: "YB",
        name: "Yanis B.",
        meta: "4 fiestas · visto el 7 sept.",
        tag: "Habitual",
        tone: "hot",
      },
      { ini: "IM", name: "Inès M.", meta: "1ª fiesta · ayer", tag: "Nueva", tone: "new" },
      {
        ini: "LD",
        name: "Lucas D.",
        meta: "3 fiestas · hace 5 meses",
        tag: "A recuperar",
        tone: "cold",
      },
      {
        ini: "SD",
        name: "Sarah D.",
        meta: "11 fiestas · vista el sábado",
        tag: "Habitual",
        tone: "hot",
      },
      {
        ini: "HM",
        name: "Hugo M.",
        meta: "2 fiestas · visto el 30 ago.",
        tag: "Ocasional",
        tone: "warm",
      },
      { ini: "NK", name: "Nora K.", meta: "1ª fiesta · Techno Night", tag: "Nueva", tone: "new" },
      {
        ini: "TG",
        name: "Théo G.",
        meta: "5 fiestas · hace 3 meses",
        tag: "A recuperar",
        tone: "cold",
      },
      {
        ini: "LP",
        name: "Léa P.",
        meta: "9 fiestas · vista el 26 sept.",
        tag: "Habitual",
        tone: "hot",
      },
      {
        ini: "AB",
        name: "Adam B.",
        meta: "2 fiestas · visto el 12 sept.",
        tag: "Ocasional",
        tone: "warm",
      },
    ] as Pill[],
    connected: "Conectado a tu cuenta de Shotgun",
    facts: [
      {
        title: "Todo tu historial",
        body: "Fiestas, entradas y compradores importados en cuanto conectas.",
      },
      { title: "Siempre al día", body: "Cada nueva entrada llega sola a tu archivo." },
      {
        title: "Solo lectura",
        body: "Yuno no modifica, no reembolsa y no publica nada en Shotgun.",
      },
    ],
  },
  problem: {
    eyebrow: "El problema",
    title: "Tu próximo habitual ya ha venido 3 veces. Solo que no sabes quién es.",
    accent: "quién es",
    sub: "Una ticketera te dice cuántas entradas se vendieron. No quién vuelve, quién desapareció ni a quién avisar.",
    cards: [
      {
        title: "Tus ventas no dicen nada de tus clientes.",
        body: "Cuántas visitas antes de comprar, de dónde vienen, dónde abandonan: Yuno muestra el recorrido, no solo la entrada.",
      },
      {
        title: "El mismo email para todos. Nadie hace clic.",
        body: "Yuno adapta emails y SMS a cada cliente, impulsados por IA y automatizaciones.",
      },
    ],
  },
  night: {
    title: "Tus entradas ya saben quién vuelve. Ahora tú también.",
    accent: "tú también",
    sub: "Cada entrada deja un nombre, una fecha, una fiesta. Yuno lo reúne todo en un solo archivo, fusiona los duplicados y ordena a tus clientes por fidelidad. Se actualiza solo.",
    table: {
      title: "Todos los clientes",
      sub: "18.420 contactos únicos · ordenados por fidelidad",
      search: "Buscar un cliente",
      filters: ["Todos", "Habituales", "Nuevos", "A recuperar"],
      export: "Exportar",
      cols: ["Cliente", "Fiestas", "Última visita", "Fidelidad", "Contactable", "Estado"],
      rows: [
        {
          ini: "SD",
          name: "Sarah Dubois",
          sub: "París 11e",
          nights: 11,
          last: "3 oct.",
          score: 98,
          reach: "E-mail · SMS",
          tag: "Habitual",
          tone: "hot",
        },
        {
          ini: "CL",
          name: "Camille Laurent",
          sub: "Montreuil",
          nights: 14,
          last: "26 sept.",
          score: 96,
          reach: "E-mail · SMS",
          tag: "Habitual",
          tone: "hot",
        },
        {
          ini: "LP",
          name: "Léa Petit",
          sub: "París 20e",
          nights: 9,
          last: "26 sept.",
          score: 91,
          reach: "E-mail",
          tag: "Habitual",
          tone: "hot",
        },
        {
          ini: "HM",
          name: "Hugo Marchand",
          sub: "París 18e",
          nights: 9,
          last: "12 sept.",
          score: 88,
          reach: "E-mail · SMS",
          tag: "Habitual",
          tone: "hot",
        },
        {
          ini: "TG",
          name: "Théo Garnier",
          sub: "Vincennes",
          nights: 5,
          last: "4 jul.",
          score: 64,
          reach: "E-mail",
          tag: "A recuperar",
          tone: "cold",
        },
        {
          ini: "AB",
          name: "Adam Benali",
          sub: "París 10e",
          nights: 2,
          last: "12 sept.",
          score: 41,
          reach: "SMS",
          tag: "Ocasional",
          tone: "warm",
        },
        {
          ini: "NK",
          name: "Nora Kaci",
          sub: "Saint-Ouen",
          nights: 1,
          last: "3 oct.",
          score: 22,
          reach: "E-mail · SMS",
          tag: "Nueva",
          tone: "new",
        },
        {
          ini: "YH",
          name: "Yanis Haddad",
          sub: "París 13e",
          nights: 1,
          last: "3 oct.",
          score: 20,
          reach: "E-mail",
          tag: "Nuevo",
          tone: "new",
        },
      ],
    },
    chipsTitle: "Que no se te escape nadie",
    chips: [
      [
        "Habituales",
        "Nuevos",
        "A recuperar",
        "Grandes fieles",
        "Duplicados fusionados",
        "Una ficha por cliente",
        "Importación CSV o Excel",
        "Búsqueda en 2 segundos",
      ],
      [
        "Informe de la fiesta",
        "Comparado con la fiesta anterior",
        "Quién compra",
        "Ritmo de ventas",
        "Ventas tras un envío",
        "Próxima fiesta",
        "Exportación cuando quieras",
      ],
      [
        "Campañas de e-mail",
        "SMS",
        "Plantillas listas",
        "Envíos programados",
        "Coste visible antes del envío",
        "Bajas gestionadas",
        "Equipo sin límite",
        "MCP · ChatGPT, Claude, Gemini",
        "Audiencias Meta · pronto",
      ],
    ],
    cta: "Conectar mi cuenta de Shotgun",
  },
  steps: {
    eyebrow: "Cómo funciona",
    title: "Yuno en 2 minutos.",
    accent: "2 minutos",
    sub: "Conectas, Yuno lo ordena todo. Nada que teclear: tus clientes están listos antes de que acabes el café.",
    cta: "Conectar mi cuenta de Shotgun",
    stepWord: "Paso",
    items: [
      {
        title: "Conecta Shotgun.",
        body: "Pega tu ID de organizador y tu token API, generados en tus integraciones de Shotgun. Sin contraseña.",
      },
      {
        title: "Yuno lo ordena todo.",
        body: "Fiestas, entradas y compradores se importan, se agrupan por persona y se ordenan por fidelidad. Luego todo se actualiza solo.",
      },
      {
        title: "Abre. Mira. Avisa.",
        body: "Cada mañana: qué se vendió, a quién avisar, qué necesita tu atención. Ya no analizas, actúas.",
      },
    ],
    connect: {
      title: "Conectar Shotgun",
      sub: "Solo lectura. Nada cambia en Shotgun.",
      id: "ID de organizador",
      idVal: "48213",
      token: "Token API",
      help: "¿Dónde encuentro mi token?",
      btn: "Conectar",
      busy: "Comprobando…",
      ok: "Conectado · sincro cada 15 min",
    },
    sort: {
      title: "Importando tu historial",
      sub: "Yuno ordena a tus clientes, tú no tienes que hacer nada.",
      rows: [
        { label: "Fiestas importadas", n: 38 },
        { label: "Entradas importadas", n: 24812 },
        { label: "Clientes agrupados", n: 18420 },
        { label: "Duplicados fusionados", n: 3106 },
      ],
      done: "Historial de Shotgun importado",
    },
  },
  channels: {
    eyebrow: "Los envíos",
    title: "Tus clientes. Tus mensajes. Un solo contador.",
    accent: "contador",
    sub: "Escribe al segmento adecuado por e-mail o SMS, mira el coste antes de enviar, prográmalo. Hoy e-mail y SMS, mañana Instagram y WhatsApp: mismo sitio, mismo contador.",
    cta: "Probar gratis 14 días",
    composer: {
      title: "Nuevo mensaje",
      to: "Para",
      cost: "Coste",
      after: "Saldo tras el envío",
      schedule: "Sábado · 18:00",
      send: "Programar",
      subject: "Asunto",
      messages: [
        {
          seg: "Habituales",
          count: 1284,
          channel: "E-mail",
          subject: "El sábado, repetimos.",
          text: "Ya son tres fiestas seguidas. Tu sitio te espera el sábado, antes que nadie.",
        },
        {
          seg: "Nuevos",
          count: 320,
          channel: "SMS",
          subject: "",
          text: "¡Gracias por venir a Techno Night! Próxima fecha el 17: yuno.fr/bunker",
        },
        {
          seg: "Dormidos",
          count: 740,
          channel: "E-mail",
          subject: "Te hemos guardado un sitio.",
          text: "Hace tiempo que no te vemos. Warehouse Sessions, viernes 9: la preventa abre primero para ti.",
        },
      ],
      balance: 8940,
    },
    rates: [
      { name: "E-mail", cost: "1 Yunit", soon: false },
      { name: "SMS", cost: "40 Yunits", soon: false },
      { name: "DM de Instagram", cost: "Pronto", soon: true },
      { name: "WhatsApp", cost: "Pronto", soon: true },
    ],
    footnote:
      "Los envíos de prueba son gratis. Yuno aparta a los contactos ya demasiado solicitados, sin contártelos.",
  },
  mcp: {
    eyebrow: "Integraciones",
    title: "Tus datos. Tu IA. Gracias al MCP.",
    accent: "MCP",
    sub: "Conecta Yuno a ChatGPT, Claude, Gemini y muchos más para convertir a tus clientes y tus ventas en análisis al instante.",
    cta: "Probar gratis 14 días",
    stage: "La IA al servicio de tus fiestas",
    stageAccent: "tus fiestas",
    placeholder: "¿Qué datos de tus clientes quieres analizar?",
    models: ["Claude", "ChatGPT", "Gemini"],
    via: "con el MCP de Yuno",
    convo: [
      {
        q: "¿Qué habituales no han vuelto en 2 meses?",
        a: "214 habituales no han comprado nada en 60 días, 168 de ellos contactables por e-mail. ¿Te preparo el segmento «A recuperar»?",
      },
      {
        q: "¿Qué fiesta trajo más clientes nuevos en septiembre?",
        a: "Techno Night del 12 sept.: 312 clientes nuevos, el 39 % de los compradores. Le sigue Warehouse Sessions con 204.",
      },
      {
        q: "¿Techno Night va por delante de la anterior?",
        a: "Sí: 842 plazas esta noche frente a 802 en el mismo momento el 12 sept., un 5 % de ventaja. A este ritmo, unas 960 plazas.",
      },
    ],
    chips: ["Analizar", "Segmentar", "Escribir", "Comparar", "Prever"],
  },
  compare: {
    title:
      "Tu ticketera te dice cuántas entradas se vendieron. Yuno te dice a quién avisar para llenar la próxima.",
    accent: "a quién avisar para llenar la próxima",
    tabs: ["Tu ticketera te da", "Yuno te da"],
    left: {
      title: "Lo que te da tu ticketera",
      items: [
        "Un total de entradas por fiesta",
        "Un export que reabrir cada vez",
        "Las mismas personas en diez archivos",
        "Ni idea de quién vuelve",
      ],
    },
    right: {
      title: "Lo que te da Yuno",
      items: [
        "Quién vuelve, y cuántas veces",
        "Una ficha por persona, para siempre",
        "Los habituales que se alejan",
        "Segmentos listos para un mensaje",
        "El informe de cada fiesta",
      ],
    },
    cta: "Probar gratis 14 días",
  },
  bento: {
    eyebrow: "Funciones",
    title: "Todo lo que tu ticketera no te enseña.",
    accent: "no te enseña",
    sub: "Una herramienta pensada para una sola cosa: convertir a tus compradores en habituales.",
    cta: "Probar gratis 14 días",
    clients: {
      title: "Archivo de clientes",
      body: "Cada comprador se convierte en una ficha, con todas sus fiestas. Duplicados fusionados, cualquiera encontrado en 2 segundos.",
      search: "Buscar un cliente",
    },
    segments: {
      title: "Segmentos",
      body: "Habituales, nuevos, dormidos: cada uno en la lista adecuada. Se actualizan solas.",
      rows: [
        { l: "Habituales", n: 1284, w: 100 },
        { l: "Nuevos", n: 962, w: 75 },
        { l: "Dormidos", n: 740, w: 58 },
        { l: "Grandes fieles", n: 118, w: 14 },
      ],
      action: "Escribir a los dormidos",
    },
    relance: {
      title: "Habituales a recuperar",
      body: "Yuno detecta a los que se alejan y te da la lista. Cada mensaje va a alguien que ya conoce tus fiestas.",
      list: "A recuperar · 214",
    },
    bilans: {
      title: "Informes de cada fiesta",
      body: "Cada fiesta comparada con la anterior, en el mismo momento. Por fin sabes qué mensaje vendió.",
      legend: ["Esta fiesta", "Tus anteriores"],
      axis: ["Apertura de ventas", "Fiesta"],
      stats: [
        { v: "842", l: "plazas vendidas" },
        { v: "+5 %", l: "vs la fiesta del 12 sept." },
        { v: "38 %", l: "de nuevos" },
      ],
      send: "E-mail «Line-up»",
    },
    envois: {
      title: "Automatizaciones",
      body: "Bienvenida, vuelta tras una ausencia, recordatorio la víspera: se configuran una vez y se envían siempre. Pausa cuando quieras.",
      flow: [
        { k: "Disparador", v: "Primera compra contigo" },
        { k: "Esperar", v: "1 día después de la fiesta" },
        { k: "E-mail", v: "«Gracias por venir»" },
      ],
    },
  },
  pricing: {
    eyebrow: "Precio",
    title: "Un solo precio. Toda la herramienta incluida.",
    accent: "incluida",
    sub: "Una pequeña suscripción fija. Después, solo pagas lo que envías.",
    monthly: "Mensual",
    annual: "Anual",
    annualNote: "Anual: **30.000 Yunits de regalo de golpe**, unos dos meses gratis.",
    plan: "Yuno CRM",
    launch: "Precio de lanzamiento",
    month: 29,
    year: 348,
    perMonth: "+ IVA / mes",
    perYear: "+ IVA / año",
    subMonthly: "Luego 39 € para los nuevos clientes. Tú mantienes 29 € mientras sigas suscrito.",
    subAnnual: "Es decir, 29 € al mes, sin descuento. Facturado una vez al año.",
    monthlyYunits: "**10.000 Yunits** de regalo cada mes",
    monthlyYunitsSub: "para enviar 10.000 e-mails",
    annualBonus: "**30.000 Yunits** más, de golpe",
    annualBonusSub: "≈ 60 € de envíos",
    cta: "Probar gratis 14 días",
    notes: ["Sin tarjeta", "5.000 Yunits de regalo durante la prueba"],
    includedTitle: "Todo incluido",
    includedSub: "Nada que desbloquear, sin extras.",
    feats: [
      { t: "Conexión Shotgun", d: "tus ventas llegan solas" },
      { t: "Archivo de clientes", d: "un solo archivo para todas tus fiestas" },
      { t: "Segmentos", d: "habituales, nuevos, a recuperar" },
      { t: "Informes de cada fiesta", d: "qué funcionó, fiesta a fiesta" },
      { t: "Campañas de e-mail", d: "y SMS, en el mismo sitio" },
      { t: "Automatizaciones", d: "bienvenida, avisos, recordatorios" },
      { t: "Audiencias Meta", d: "tus segmentos en anuncios · pronto" },
      { t: "Asistente IA", d: "gratis, sin contar" },
      { t: "Tu IA con el MCP", d: "ChatGPT, Claude, Gemini" },
      { t: "Equipo sin límite", d: "ningún puesto que pagar" },
    ],
    vat: "Precios sin IVA. El IVA se añade a la factura.",
    yunits: {
      eyebrow: "Los Yunits",
      title: "¿Qué es un Yunit?",
      soon: "Pronto",
      rates: [
        { name: "E-mail", cost: 1, soon: false },
        { name: "SMS", cost: 40, soon: false },
        { name: "DM de Instagram", cost: 10, soon: true },
        { name: "WhatsApp", cost: 100, soon: true },
      ],
      accent: "Yunit",
      sub: "La moneda de la herramienta. Cada envío consume unos cuantos, y cada mes te regalamos 10.000 con tu suscripción.",
      free: "Siempre gratis",
      freeItems: [
        "Los envíos de prueba",
        "El asistente IA",
        "Los contactos que Yuno aparta para no saturarlos",
      ],
      eq: "10.000 Yunits son 10.000 e-mails, o 250 SMS, o una mezcla de ambos.",
      wallet: "Tu saldo",
      chip: ["Regalados + comprados", "Saldo bajo", "Recargado"],
      rows: [
        { t: "Campaña «Sábado»", s: "2.200 e-mails", d: "− 2.200", k: "minus" },
        { t: "Aviso por SMS", s: "60 contactos", d: "− 2.400", k: "minus" },
        { t: "Envío de prueba", s: "enviado a ti mismo", d: "Gratis", k: "free" },
        { t: "Asistente IA", s: "12 preguntas", d: "Gratis", k: "free" },
        { t: "Campaña «Brunch»", s: "5.000 e-mails", d: "− 5.000", k: "minus" },
        { t: "Recarga de 10 €", s: "en un clic", d: "+ 5.000", k: "plus" },
      ],
    },
    sim: {
      title: "¿Cuánto me costará el mes?",
      sub: "Elige un perfil o ajusta tus envíos. El cálculo usa las recargas reales, al mejor precio.",
      presets: [
        { id: "asso", label: "Equipo pequeño", desc: "4000 e-mails", e: 4000, s: 0 },
        {
          id: "orga",
          label: "Organizador semanal",
          desc: "45.000 e-mails · 300 SMS",
          e: 45000,
          s: 300,
        },
        { id: "club", label: "Club activo", desc: "90.000 e-mails · 500 SMS", e: 90000, s: 500 },
      ],
      emails: "E-mails al mes",
      sms: "SMS al mes",
      estimate: "Estimación · al mes",
      subscription: "Suscripción",
      sends: "Tus envíos",
      included: "Regalados con la suscripción",
      recharges: "Recargas",
      enough: "Tus Yunits de regalo bastan: ninguna recarga.",
      left: "Te quedan {n} Yunits tras este mes, válidos un año.",
      exact: "Justo lo necesario.",
      offered: "Regalados",
      bought: "Recargados",
    },
  },
  faq: {
    eyebrow: "FAQ",
    title: "Preguntas frecuentes.",
    accent: "frecuentes",
    sub: "¿Otra pregunta? Escríbenos, respondemos el mismo día.",
    email: "contact@yunoapp.eu",
    items: [
      {
        q: "¿Yuno cambia algo en Shotgun?",
        a: "No. Yuno solo lee: no crea, no reembolsa, no escanea y no publica nada. Puedes cortar la conexión cuando quieras, desde Yuno o desde Shotgun.",
      },
      {
        q: "¿Tengo que dar mi contraseña?",
        a: "No. Generas un token en las integraciones de Shotgun y lo pegas en Yuno con tu ID de organizador. Solo sirve para leer tus datos y se borra al desconectar.",
      },
      {
        q: "¿Cuánto tardo en ver a mis clientes?",
        a: "La conexión lleva unos 2 minutos. Después Yuno importa todo tu historial (fiestas, entradas, compradores) y tus clientes aparecen ordenados por fidelidad.",
      },
      {
        q: "¿Puedo escribir a todos mis compradores?",
        a: "Solo reciben tus mensajes quienes aceptaron recibir tus e-mails. Los demás cuentan en tus cifras, sin recibir nada. Cada mensaje incluye además la baja.",
      },
      {
        q: "¿Yuno lee mis estadísticas de Instagram?",
        a: "No, Yuno no tiene acceso a los datos de Instagram. Mide lo que pasa por él: tus ventas de Shotgun, tus e-mails y SMS, los clics en tus enlaces de Yuno.",
      },
      {
        q: "¿Puedo conectar ChatGPT, Claude o Gemini?",
        a: "Sí, con el MCP de Yuno. Conectas tu IA en unos clics y le preguntas por tus clientes, tus fiestas y tus envíos: responde con tus cifras reales. Puedes cortar el acceso cuando quieras.",
      },
      {
        q: "¿Y si no uso Shotgun?",
        a: "Hoy, la conexión automática es la de Shotgun. Desde cualquier otra herramienta, importa tu archivo de clientes (CSV o Excel): se une a la misma base, sin duplicados.",
      },
      {
        q: "¿Cuánto cuesta, y después de los 14 días?",
        a: "29 € + IVA al mes, con 10.000 Yunits de regalo cada mes para tus envíos. Sin suscripción al final de la prueba, la cuenta se pone en pausa: sigues viendo tu base, no sale nada.",
      },
      {
        q: "¿Qué pasa si me faltan Yunits?",
        a: "Antes de cada envío, Yuno muestra su coste y tu saldo. Si faltan, recargas sin salir de la pantalla y el envío continúa. Los regalados se usan primero; los comprados son válidos un año.",
      },
      {
        q: "¿Puede subir el precio de 29 €?",
        a: "El precio pasará a 39 € más adelante, solo para los nuevos clientes. Si te suscribes a 29 €, mantienes ese precio mientras sigas suscrito.",
      },
      {
        q: "¿Dónde se alojan mis datos?",
        a: "En Europa. Puedes exportar tus clientes o borrarlo todo cuando quieras, sin cambiar nada en Shotgun.",
      },
    ],
  },
  final: {
    title: "Tu próxima fiesta ya se está vendiendo. Sabe quién viene.",
    accent: "quién viene",
    sub: "Conecta Shotgun en 2 minutos y recupera a todos tus clientes. 14 días de prueba, sin tarjeta.",
    cta: "Probar gratis 14 días",
  },
  footer: {
    tagline: "El archivo de clientes de discotecas y organizadores de fiestas.",
    cols: [
      {
        title: "Producto",
        links: [
          { label: "Funciones", href: "#fonctionnalites" },
          { label: "Cómo funciona", href: "#etapes" },
          { label: "Precios", href: "#tarifs" },
        ],
      },
      {
        title: "Ayuda",
        links: [
          { label: "FAQ", href: "#faq" },
          { label: "Hablar con el fundador", href: "whatsapp" },
          { label: "Entrar", href: "login" },
        ],
      },
      {
        title: "Legal",
        links: [
          { label: "Condiciones", href: "/terms" },
          { label: "Privacidad", href: "/privacy" },
        ],
      },
    ],
    region: "Datos alojados en Europa",
    rights: "Yuno",
    suite: "¿También quieres vender tus entradas? Descubre Yuno Ticketing",
  },
  mobileCta: "Probar gratis 14 días",
  signup: {
    roleTitle: "¿Quién conecta su ticketera?",
    roles: [
      { id: "club", label: "Una discoteca o sala", hint: "Tus fiestas y tus habituales" },
      { id: "organizer", label: "Fiestas y eventos", hint: "Organizador o colectivo" },
      { id: "promoter", label: "Un equipo de promo", hint: "Promotor o agencia" },
      { id: "other", label: "Otra cosa", hint: "Festival, bar, DJ…" },
    ],
    roleSub: "Yuno CRM prepara tu consola para ello — dos minutos, sin llamada.",
    structureSub: "Tu consola y tus primeros informes se construyen con esto.",
    tool: "Tu ticketera",
    toolHint: "Shotgun se conecta directamente; para las demás, importarás tu archivo de clientes.",
  },
};

export const crmContent: Record<"en" | "fr" | "es", CrmContent> = { en, fr, es };
