// Legal page copy (Privacy + Terms), available in every locale. Routes read the
// raw `legalContent[locale]` map inside head() for meta/SEO; components read it
// via useLegal(). French is checked against the English shape at compile time
// (LegalContent = typeof en), so keys and section array lengths must match.
import { useLocale, type Locale } from "@/i18n/locale";

const en = {
  privacy: {
    meta: {
      title: "Privacy Policy — Yuno",
      description:
        "How Yuno collects, uses and protects personal data for clubs, organizers, promoters and their guests.",
    },
    heading: "Privacy Policy",
    lastUpdated: "Last updated: September 16, 2026",
    badge: "Legal",
    summaryLabel: "Summary",
    notice:
      "This page summarises how Yuno handles personal data. The full Privacy Policy, together with our Cookie Policy and our Article 28 Data Processing Agreement, is published on the platform:",
    canonicalLabel: "Read the full Privacy Policy",
    canonicalHref: "https://www.yunoapp.eu/legal/privacy",
    sections: [
      {
        title: "What we collect",
        body:
          "Account data (name, email, role), operational data generated by your use of Yuno (events, orders, table reservations), and the minimum guest data required to deliver tickets and Click & Collect orders.",
      },
      {
        title: "How we use it",
        body:
          "To run the platform, process payments through Stripe Connect, send transactional notifications, and provide analytics dashboards to venue operators, organizers and promoters.",
      },
      {
        title: "Advertising and measurement",
        body:
          "Venues and organizers can connect their own Meta business assets (dataset / pixel, ad account, Page, lead forms) to their Yuno account. When a guest has given advertising consent, Yuno sends that venue's own ticket, table and drink purchases to that venue's own Meta dataset so the venue can measure its own ads, and can build custom audiences in the venue's own ad account from contacts who agreed to receive its marketing. Each venue's data is used only for that venue. We never combine data between venues, never sell it, and never use it for Yuno's own advertising. Consent can be withdrawn at any time from the Cookies menu.",
      },
      {
        title: "Who we share it with",
        body:
          "The venue or organizer you bought from, as the seller of record. Stripe, for payment processing. Supabase, for hosting inside the EU. Resend and Twilio, for the emails and text messages you agreed to receive. Meta, only for the venues and organizers who connected their own advertising account, and only for guests who gave advertising consent. We have no other recipients, and we sell personal data to no one.",
      },
      {
        title: "How long we keep it, and how to have it deleted",
        body:
          "Account and order data is kept for as long as your account exists, then for the legal retention period that applies to sales records. You can delete your account at any time from the app, which erases your account and the personal data attached to it. A venue or organizer can disconnect its advertising account at any time, which stops any further sharing with Meta and deletes the stored access. To have data deleted without going through the app, write to contact@yunoapp.eu and we answer within one month, as the GDPR requires.",
      },
      {
        title: "Your rights",
        body:
          "Access, rectification, deletion, portability and objection rights under the GDPR. Email us to exercise any of them.",
      },
    ],
  },
  terms: {
    meta: {
      title: "Terms of Service — Yuno",
      description:
        "The terms governing use of the Yuno platform by clubs, organizers, promoters and their guests.",
    },
    heading: "Terms of Service",
    lastUpdated: "Last updated: September 16, 2026",
    badge: "Legal",
    summaryLabel: "Summary",
    notice:
      "This page summarises the terms of use. The full Terms of Service, the sales terms for venues and for guests, and the legal notice identifying the publisher, are published on the platform:",
    canonicalLabel: "Read the full Terms of Service",
    canonicalHref: "https://www.yunoapp.eu/legal/cgu",
    sections: [
      {
        title: "Using Yuno",
        body:
          "By creating an account you agree to operate within the platform's intended use: hosting and operating nightlife events, processing ticket sales and bar / VIP transactions in compliance with local law.",
      },
      {
        title: "Fees & payments",
        body:
          "Plan and transactional fees are described on the Pricing page. Payments are processed through Stripe Connect; each connected account is bound by Stripe's own terms.",
      },
      {
        title: "Liability",
        body:
          "Yuno provides the platform \"as is\" while we finalize service-level commitments. Operators remain responsible for ticket validity, capacity enforcement and on-site decisions.",
      },
    ],
    pricingLink: "Pricing page",
  },
};

export type LegalContent = typeof en;

const fr: LegalContent = {
  privacy: {
    meta: {
      title: "Politique de confidentialité — Yuno",
      description:
        "Comment Yuno collecte, utilise et protège les données personnelles des clubs, organisateurs, promoteurs et de leurs invités.",
    },
    heading: "Politique de confidentialité",
    lastUpdated: "Dernière mise à jour : 16 septembre 2026",
    badge: "Mentions légales",
    summaryLabel: "Résumé",
    notice:
      "Cette page résume la façon dont Yuno traite les données personnelles. La Politique de confidentialité complète, la Politique cookies et l'accord de sous-traitance (article 28 du RGPD) sont publiés sur la plateforme :",
    canonicalLabel: "Lire la Politique de confidentialité complète",
    canonicalHref: "https://www.yunoapp.eu/legal/confidentialite",
    sections: [
      {
        title: "Ce que nous collectons",
        body:
          "Les données de compte (nom, e-mail, rôle), les données opérationnelles générées par votre utilisation de Yuno (événements, commandes, réservations de tables) et le minimum de données invités nécessaires à la délivrance des billets et des commandes Click & Collect.",
      },
      {
        title: "Comment nous l'utilisons",
        body:
          "Pour faire fonctionner la plateforme, traiter les paiements via Stripe Connect, envoyer les notifications transactionnelles et fournir des tableaux de bord d'analyse aux exploitants d'établissements, organisateurs et promoteurs.",
      },
      {
        title: "Publicité et mesure",
        body:
          "Les clubs et les organisateurs peuvent connecter à leur compte Yuno leurs propres actifs professionnels Meta (jeu de données / pixel, compte publicitaire, Page, formulaires de prospects). Lorsque le client a donné son consentement publicitaire, Yuno transmet les achats de billets, de tables et de consommations de ce lieu au jeu de données Meta de ce même lieu, afin qu'il mesure ses propres publicités, et peut créer dans son compte publicitaire des audiences personnalisées à partir des contacts qui ont accepté de recevoir ses communications. Les données d'un lieu ne servent qu'à ce lieu. Nous ne croisons jamais les données entre lieux, ne les vendons jamais et ne les utilisons jamais pour la publicité de Yuno. Le consentement est retirable à tout moment via le menu Cookies.",
      },
      {
        title: "Avec qui nous les partageons",
        body:
          "Le club ou l'organisateur auprès duquel vous avez acheté, en qualité de vendeur. Stripe, pour le traitement des paiements. Supabase, pour l'hébergement dans l'Union européenne. Resend et Twilio, pour les emails et SMS que vous avez acceptés. Meta, uniquement pour les clubs et organisateurs qui ont connecté leur propre compte publicitaire, et uniquement pour les clients ayant donné leur consentement publicitaire. Il n'y a aucun autre destinataire, et nous ne vendons de données personnelles à personne.",
      },
      {
        title: "Combien de temps, et comment faire supprimer vos données",
        body:
          "Les données de compte et de commande sont conservées tant que votre compte existe, puis pendant la durée légale applicable aux pièces de vente. Vous pouvez supprimer votre compte à tout moment depuis l'application : le compte et les données personnelles qui s'y rattachent sont effacés. Un club ou un organisateur peut déconnecter son compte publicitaire à tout moment, ce qui arrête tout partage ultérieur avec Meta et efface l'accès conservé. Pour une suppression sans passer par l'application, écrivez à contact@yunoapp.eu : nous répondons sous un mois, comme l'exige le RGPD.",
      },
      {
        title: "Vos droits",
        body:
          "Droits d'accès, de rectification, de suppression, de portabilité et d'opposition au titre du RGPD. Écrivez-nous pour exercer l'un de ces droits.",
      },
    ],
  },
  terms: {
    meta: {
      title: "Conditions d'utilisation — Yuno",
      description:
        "Les conditions régissant l'utilisation de la plateforme Yuno par les clubs, organisateurs, promoteurs et leurs invités.",
    },
    heading: "Conditions d'utilisation",
    lastUpdated: "Dernière mise à jour : 16 septembre 2026",
    badge: "Mentions légales",
    summaryLabel: "Résumé",
    notice:
      "Cette page résume les conditions d'utilisation. Les Conditions générales d'utilisation complètes, les CGV clubs et utilisateurs ainsi que les mentions légales identifiant l'éditeur sont publiées sur la plateforme :",
    canonicalLabel: "Lire les Conditions d'utilisation complètes",
    canonicalHref: "https://www.yunoapp.eu/legal/cgu",
    sections: [
      {
        title: "Utilisation de Yuno",
        body:
          "En créant un compte, vous acceptez d'utiliser la plateforme conformément à sa finalité : organiser et exploiter des événements de vie nocturne, traiter les ventes de billets et les transactions bar / VIP dans le respect de la législation locale.",
      },
      {
        title: "Frais & paiements",
        body:
          "Les frais d'abonnement et de transaction sont décrits sur la page Tarifs. Les paiements sont traités via Stripe Connect ; chaque compte connecté est soumis aux propres conditions de Stripe.",
      },
      {
        title: "Responsabilité",
        body:
          "Yuno fournit la plateforme « en l'état » pendant que nous finalisons nos engagements de niveau de service. Les exploitants restent responsables de la validité des billets, du respect de la capacité et des décisions prises sur place.",
      },
    ],
    pricingLink: "page Tarifs",
  },
};

export const legalContent: Record<Locale, LegalContent> = { en, fr };

export function useLegal(): LegalContent {
  return legalContent[useLocale()];
}
