/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OrganizersRouteImport } from './routes/organizers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as AffiliatesRouteImport } from './routes/affiliates'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FrIndexRouteImport } from './routes/fr/index'
import { Route as FrTermsRouteImport } from './routes/fr/terms'
import { Route as FrPrivacyRouteImport } from './routes/fr/privacy'
import { Route as FrPricingRouteImport } from './routes/fr/pricing'
import { Route as FrOrganizersRouteImport } from './routes/fr/organizers'
import { Route as FrContactRouteImport } from './routes/fr/contact'
import { Route as FrClubsRouteImport } from './routes/fr/clubs'
import { Route as FrAffiliatesRouteImport } from './routes/fr/affiliates'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizersRoute = OrganizersRouteImport.update({
  id: '/organizers',
  path: '/organizers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesRoute = AffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrIndexRoute = FrIndexRouteImport.update({
  id: '/fr/',
  path: '/fr/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrTermsRoute = FrTermsRouteImport.update({
  id: '/fr/terms',
  path: '/fr/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const FrPrivacyRoute = FrPrivacyRouteImport.update({
  id: '/fr/privacy',
  path: '/fr/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FrPricingRoute = FrPricingRouteImport.update({
  id: '/fr/pricing',
  path: '/fr/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FrOrganizersRoute = FrOrganizersRouteImport.update({
  id: '/fr/organizers',
  path: '/fr/organizers',
  getParentRoute: () => rootRouteImport,
} as any)
const FrContactRoute = FrContactRouteImport.update({
  id: '/fr/contact',
  path: '/fr/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FrClubsRoute = FrClubsRouteImport.update({
  id: '/fr/clubs',
  path: '/fr/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const FrAffiliatesRoute = FrAffiliatesRouteImport.update({
  id: '/fr/affiliates',
  path: '/fr/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affiliates': typeof AffiliatesRoute
  '/clubs': typeof ClubsRoute
  '/contact': typeof ContactRoute
  '/organizers': typeof OrganizersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/fr/affiliates': typeof FrAffiliatesRoute
  '/fr/clubs': typeof FrClubsRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/organizers': typeof FrOrganizersRoute
  '/fr/pricing': typeof FrPricingRoute
  '/fr/privacy': typeof FrPrivacyRoute
  '/fr/terms': typeof FrTermsRoute
  '/fr/': typeof FrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affiliates': typeof AffiliatesRoute
  '/clubs': typeof ClubsRoute
  '/contact': typeof ContactRoute
  '/organizers': typeof OrganizersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/fr/affiliates': typeof FrAffiliatesRoute
  '/fr/clubs': typeof FrClubsRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/organizers': typeof FrOrganizersRoute
  '/fr/pricing': typeof FrPricingRoute
  '/fr/privacy': typeof FrPrivacyRoute
  '/fr/terms': typeof FrTermsRoute
  '/fr': typeof FrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affiliates': typeof AffiliatesRoute
  '/clubs': typeof ClubsRoute
  '/contact': typeof ContactRoute
  '/organizers': typeof OrganizersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/fr/affiliates': typeof FrAffiliatesRoute
  '/fr/clubs': typeof FrClubsRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/organizers': typeof FrOrganizersRoute
  '/fr/pricing': typeof FrPricingRoute
  '/fr/privacy': typeof FrPrivacyRoute
  '/fr/terms': typeof FrTermsRoute
  '/fr/': typeof FrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affiliates'
    | '/clubs'
    | '/contact'
    | '/organizers'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/fr/affiliates'
    | '/fr/clubs'
    | '/fr/contact'
    | '/fr/organizers'
    | '/fr/pricing'
    | '/fr/privacy'
    | '/fr/terms'
    | '/fr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affiliates'
    | '/clubs'
    | '/contact'
    | '/organizers'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/fr/affiliates'
    | '/fr/clubs'
    | '/fr/contact'
    | '/fr/organizers'
    | '/fr/pricing'
    | '/fr/privacy'
    | '/fr/terms'
    | '/fr'
  id:
    | '__root__'
    | '/'
    | '/affiliates'
    | '/clubs'
    | '/contact'
    | '/organizers'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/fr/affiliates'
    | '/fr/clubs'
    | '/fr/contact'
    | '/fr/organizers'
    | '/fr/pricing'
    | '/fr/privacy'
    | '/fr/terms'
    | '/fr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffiliatesRoute: typeof AffiliatesRoute
  ClubsRoute: typeof ClubsRoute
  ContactRoute: typeof ContactRoute
  OrganizersRoute: typeof OrganizersRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  FrAffiliatesRoute: typeof FrAffiliatesRoute
  FrClubsRoute: typeof FrClubsRoute
  FrContactRoute: typeof FrContactRoute
  FrOrganizersRoute: typeof FrOrganizersRoute
  FrPricingRoute: typeof FrPricingRoute
  FrPrivacyRoute: typeof FrPrivacyRoute
  FrTermsRoute: typeof FrTermsRoute
  FrIndexRoute: typeof FrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizers': {
      id: '/organizers'
      path: '/organizers'
      fullPath: '/organizers'
      preLoaderRoute: typeof OrganizersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates': {
      id: '/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/': {
      id: '/fr/'
      path: '/fr'
      fullPath: '/fr/'
      preLoaderRoute: typeof FrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/terms': {
      id: '/fr/terms'
      path: '/fr/terms'
      fullPath: '/fr/terms'
      preLoaderRoute: typeof FrTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/privacy': {
      id: '/fr/privacy'
      path: '/fr/privacy'
      fullPath: '/fr/privacy'
      preLoaderRoute: typeof FrPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/pricing': {
      id: '/fr/pricing'
      path: '/fr/pricing'
      fullPath: '/fr/pricing'
      preLoaderRoute: typeof FrPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/organizers': {
      id: '/fr/organizers'
      path: '/fr/organizers'
      fullPath: '/fr/organizers'
      preLoaderRoute: typeof FrOrganizersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/contact': {
      id: '/fr/contact'
      path: '/fr/contact'
      fullPath: '/fr/contact'
      preLoaderRoute: typeof FrContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/clubs': {
      id: '/fr/clubs'
      path: '/fr/clubs'
      fullPath: '/fr/clubs'
      preLoaderRoute: typeof FrClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/affiliates': {
      id: '/fr/affiliates'
      path: '/fr/affiliates'
      fullPath: '/fr/affiliates'
      preLoaderRoute: typeof FrAffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffiliatesRoute: AffiliatesRoute,
  ClubsRoute: ClubsRoute,
  ContactRoute: ContactRoute,
  OrganizersRoute: OrganizersRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  FrAffiliatesRoute: FrAffiliatesRoute,
  FrClubsRoute: FrClubsRoute,
  FrContactRoute: FrContactRoute,
  FrOrganizersRoute: FrOrganizersRoute,
  FrPricingRoute: FrPricingRoute,
  FrPrivacyRoute: FrPrivacyRoute,
  FrTermsRoute: FrTermsRoute,
  FrIndexRoute: FrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
